### ISSUE TITLE
FR: Add mosh

### ISSUE THREAD

**Issue by stevenroose** [fort-nix/nix-bitcoin#111]
Just a wishlist item. It's really horrible to have to use SSH over Tor. It often takes several 100ms roundtrip.

**Comment by jonasnick** [comment]
Seems like adding
```
networking.firewall.allowedUDPPorts = [ 60001];
programs.mosh.enable = true;
```
to your configuration would do the trick? I don't think nix-bitcoin can make this much simpler.

**Comment by stevenroose** [comment]
`programs.mosh` is a thing? Where to `programs.*` come from? Is that like the default app directory or something? How does UDP port 60001 work together with Tor?

**Comment by nixbitcoin** [comment]
Another option would be VPNing into your nix-bitcoin node's private network.

**Comment by nixbitcoin** [comment]
Closing because of lack of interest in including this feature in master and because easy fix has been provided
