### ISSUE TITLE
Is it possible to build this nix configuration in a nixos/nix docker container ?

### ISSUE THREAD

**Issue by primeroz** [fort-nix/nix-bitcoin#121]
This is a request for information.

I have a small familiarity with nix but not a big one.

I was wondering if is possible to build this configuration.nix into a `nixos/nix` container 

I did try to follow the guides here but after running "nix-shell" i was stuck

I would have hoped to run `nix-build` but that is not even available inside the container.

thanks

**Comment by jonasnick** [comment]
I'm surprised that nix-build isn't available in the container ([[1]](https://github.com/NixOS/docker), [[2]](https://medium.com/@danidiaz/getting-to-play-with-nix-on-windows-using-docker-a3515a6c944a)). Just because I'm curious, why do you want to do this in the first place?

**Comment by primeroz** [comment]
Mostly i wanted to test && understand how the project works, I have plenty of CoreOS lying around the globe an dusing a docker container to build this would be ideal for testing it 

on the `nix-build` side, you are right i am an idiot , what i meant was `nixos-rebuild` and that is the only way i know how to switch / rebuild based on a configuration.nix 

how would you use nix-build to build this configuration in a scratch `nixos/nix` container ? 
Is this just a stupid idea and instead i should just start a VM somewhere ? 

thanks!

**Comment by jonasnick** [comment]
Sorry, forgot about this issue. `nixos-rebuild` is a nixos-specific command and therefore not available in the nix container (which is supposed to install the nix package manager). If you're looking for a target for nix-bitcoin, you can use a VM for example with VirtualBox as explained in the [docs](https://github.com/fort-nix/nix-bitcoin/blob/master/docs/install.md#tutorials).

**Comment by primeroz** [comment]
It make sense, i ll give it a shot with "libvirt" :) 

thanks for following up on it
