### ISSUE TITLE
banlist should honor dataDir setting

### ISSUE THREAD

**Issue by fiksn** [fort-nix/nix-bitcoin#129]
In pkgs/banlist/banlist.sh there is:

```
echo "Importing node banlist into bitcoind"
# banlist taken from https://people.xiph.org/~greg/banlist.cli.txt
$1/bin/bitcoin-cli -datadir=/var/lib/bitcoind setban 100.34.232.70/32 add 31557600
```

But in nix-bitcoin/modules/bitcoind.nix I can see there is a

```
dataDir = mkOption {
        type = types.path;
        default = "/var/lib/bitcoind";
        description = "The data directory for bitcoind.";
```
Problem is that I have/want to have **services.bitcoind.dataDir** configured to a different directory than /var/lib/bitcoind.

**Comment by jonasnick** [comment]
Yes it should. Thanks for opening the issue.

**Comment by erikarvstedt** [comment]
@jonasnick, I have an overhauled banlist importer in the pipeline which fixes this and some other issues. I wanted to publish some other testing-related stuff first, to make testing my PRs easier for you and other reviewers, but I guess I'll start with the banlist stuff. I'll add a PR later this day.
