### ISSUE TITLE
Add ability to install declaratively into an existing nixos system

### ISSUE THREAD

**Issue by reardencode** [fort-nix/nix-bitcoin#135]
I tried to get this working, but ran into an issue I didn't understand.

See https://gitlab.com/simple-nixos-mailserver/nixos-mailserver for an example of a nixos-based project that can be installed via nixops, directly via a local `configuration.nix` or in a container easily.

I tried this config:
```
{ config, lib, pkgs, ... }:

{
  containers.nix-bitcoin = {
    config = {
      imports = [
        (builtins.fetchGit {
          url = "https://github.com/fort-nix/nix-bitcoin.git";
          rev = "6c69eb857617e8c6baec09a149bad29e8d829f7c";
        })
      ];
      services.nix-bitcoin.enable = true;
    };
  };
}
```

And got: `error: The option `containers.nix-bitcoin.outPath' defined in `<unknown-file>' does not exist.`

**Comment by jonasnick** [comment]
Hi. Using nix-bitcoin on an existing NixOS installation is something we're not supporting quite yet. There's PR #133 which modularizes the individual parts to make this much easier. I don't understand your error message either, but if you want to experiment more you can try with #133.

**Comment by reardencode** [comment]
Gotcha. I figured it wasn't something you were aiming to support, but was surprised that it didn't just work by default. I'll check out #133.

It does seem a bit weird to create a declarative bitcoin node configuration system, but then not be able to instantiate a node declaratively in a NixOS system.

**Comment by erikarvstedt** [comment]
@reardencode, I'm the author of #133 which targets your exact use case.
Here's a [demo script](https://gist.github.com/erikarvstedt/5db4fa7dd3f1137920b58e39647116f6) that shows how to use nix-bitcoin in a container. Use #133 as the `nixBitcoin` source.

**Comment by nixbitcoin** [comment]
Can I close as abcee651d3c24213b5efddf7e1532a6eafa70600 has been merged into master?

**Comment by erikarvstedt** [comment]
Yes.
