### ISSUE TITLE
Support having another username for "operator"

### ISSUE THREAD

**Issue by stevenroose** [fort-nix/nix-bitcoin#145]

**Comment by nixbitcoin** [comment]
I think this adds an unneeded degree of complexity. For me it also creates an unnecessary opportunity to doxx myself when sharing screenshots/code snippets. Open to other opinions though @jonasnick .

**Comment by erikarvstedt** [comment]
It would be rather simple to implement, the only prerequisite is to convert `pkgs/nodeinfo` to a module.
Also, the feature can be helpful when nix-bitcoin is used as part of a larger Nixos config that already has a operator-like user.

**Comment by nixbitcoin** [comment]
Ok, I'll take a look at it
