### ISSUE TITLE
Broken Travis integration

### ISSUE THREAD

**Issue by erikarvstedt** [fort-nix/nix-bitcoin#161]
Travis still [runs PR jobs](https://travis-ci.org/github/fort-nix/nix-bitcoin/pull_requests), but they aren't shown anymore in Github's PR views, like [here](https://github.com/fort-nix/nix-bitcoin/pull/152).

@nixbitcoin, the breakage coincided with your recent contributions and the new PR labeling automation. Did you change anything?

**Comment by jonasnick** [comment]
Hm, many projects experienced similar issues with travis recently. I've heard the solution is usually to revoke and re-enable travis' access. I tried that, but it didn't help.

**Comment by nixbitcoin** [comment]
Looks like Travis is running again
