### ISSUE TITLE
Run services using clightning under different users

### ISSUE THREAD

**Issue by jonasnick** [fort-nix/nix-bitcoin#170]
Currently these services run under the clightning user because clightnings RPC socket is only readable by the owner. However, there's a flag now to set the permissions on the RPC socket, which would allow making it group readable:
```
lightning --rpc-file-mode <arg>                Set the file mode (permissions) for the JSON-RPC socket (default: "0600")
```

**Comment by nixbitcoin** [comment]
Already updated in an unpushed branch.

I updated lightning-charge to use the group writeable and readable socket. I left the lightning-cli option because I think it isn't a good idea to run lightning-cli as root under nodeinfo or as any other user than clightning in general.
