### ISSUE TITLE
Collaboration with Cryptoanarchy deb repository?

### ISSUE THREAD

**Issue by Kixunil** [fort-nix/nix-bitcoin#175]
Hi, I work on a very similar project as you do, but focused on packaging for Debian 10. The infrastructure is here: http://github.com/Kixunil/cryptoanarchy-deb-repo-builder/
The output result is here: https://deb.ln-ask.me

I see we have very similar general approach (isolation of services, security, packaging instead of docker craziness...) and I wonder if we can join forces somehow.

**But Debian is a completely different OS, how do you want to join forces on that?!**

From my experience a lot of work when it comes to packaging is reading enough documentation (sometimes even source code) of the project and turning it into high-level specification, sometimes filing bug reports or documentation requests to various projects.

Can we share a common language for defining this high-level specification of each package? Then we could "compile" it into OS-specific one.

Gains:
* You get one [very](https://github.com/Kixunil/) dedicated contributor
* We all get several new packages (btcpayserver, ridetheln, c-lightning) already
* We all get double the output for the same amount of work - suddenly you can target Debian (which may not be as nice as Nix in certain aspects, but has more users - the reason I started working on that) and I can target Nix as a by product
* You get some freedom-related non-bitcoin packages in the future
* You get access to the SDK I'm planning to develop in the future. The SDK will aim at making it easier to develop new LNP/BP-enabled apps

Costs:
* We need to decide on a common language
* At least one side has to implement a transpiler/compiler
* We either need to align our policies in some aspects or have the language expressive enough to implement different policies (I'd aim for a balanced mix of both approaches)

I've noticed you have "your own" (nix-defined) high-level language that has some features my doesn't (and I want them) and I developed my own, which may have features interesting for you ("compiler" in [`debcrafter`](http://github.com/Kixunil/debcrafter/) repository)

For instance, I try hard to avoid tedious writing of things that are easy to typo. You define a user for each service manually. Debcrafter assumes a new user named same as the package (I plan to start prefixing them with underscore though), unless there's explicit exception. There's bunch of other similar rules (creation of paths, triggers...) I found the hard way, why such things are important (after spending hours on debugging stupid stuff like a typo in a path). This also affects security (Did I forget to set the appropriate permissions somewhere?) Even after developing Debcrafter, I figured it's still not enough!

My vision is to generate "header files" for statically checked languages (Rust at least) from that specification, so that correctness of various helper "scripts" can be statically checked. I figured, you don't have that problem because nix language is more expressive in this regard. But I wonder what happens if you attempt to use a non-existing variable or one with a wrong type.

I hope this is a good enough high-level overview of what I'm thinking about. I'm not going to make it longer right now, but I'm certain I will need to document my project better if there's any interest from your side. Please let me know. I'm willing to discuss it over an audio/video call if that works for you better. I have a feeling that it'd be more efficient.

**Comment by jonasnick** [comment]
Hey, thank you for reaching out. cryptoanarchy-deb-repo-builder looks impressive. Moreover, it addresses the most common criticism I get when mentioning nix-bitcoin: "No one uses NixOS, why don't you just build on Debian".*

The idea of defining a common high level spec language sounds quite ambitious. I don't have a good intuition for how this could benefit both projects without becoming a years long research project. For nix-bitcoin it's more natural to first focus on modules the contributors are themselves interested in and then use that as a starting point to build abstractions. HopefullyThe alternative of forcing a top-down onto the project structure would be difficult because the requirements and the general project direction are unclear.

I'm pretty sure that both projects can benefit each other in any case: by nudging developers into making packaging easy and offering sensible configuration options.

> But I wonder what happens if you attempt to use a non-existing variable or one with a wrong type.

It'll give you an error. Nix is just fun to work with - you should try it :) (for example by going through the "nix pills")

\* My answer is usually that NixOS is a more systematic approach and therefore more fun and easy to maintain. But given enough resources you can probably do something similar with other distros as well which seems to be what you're attempting to do.

**Comment by Kixunil** [comment]
Thank you for reply!

I had the idea of having a more abstract representation of packages, when I started packaging for Debian and it sounded ambitious to me too. After a few days of debugging stupid stringly bugs, I realized it's not ambitious, but necessary. So I took some time to implement MVP version of `debcrafter`, which helped quite a bit, as I don't have to repeat same things. By wanting to have something done ASAP, I cut many corners, some I didn't even understand fully. This kicked me hard recently, because the feedback loop is too long. But it gave me shitton of experience that I can share.

A way we could help each other without spending years on "ambitious projects" would be to identify very clear common things we do and try to unify them first. One of the obvious is the configuration. If we can have same files specifying the configuration, we can just include them in our projects and benefit from the other researching the config already. In special cases like `electrs` and `btc-rpc-proxy`, it could be generated from `config_spec.toml`.

There's a part of configuration that I consider special - interfaces. It's usually one or more of these settings:

* host
* port
* auth token/cookie file
* TLS cert

I'm planning to write some code to make this part more systematic, hoping to avoid duplicating settings and possibly automatically deduce dependencies.

Another idea I got is we could review each-other project and try to comment on things that could be improved based on the experience of each other. What do you think?

> It'll give you an error. Nix is just fun to work with - you should try it :)

Sounds great! It's definitely on my list of things I want to do in my life. Maybe not in the following months, but eventually. :)

**Comment by nixbitcoin** [comment]
> Another idea I got is we could review each-other project and try to comment on things that could be improved based on the experience of each other. What do you think?

This is a great idea. I'll get on this when I've completed my planned cleaning, hardening, and documenting work.

**Comment by Kixunil** [comment]
Great! I'd like to ask you to open a separate issue for everything you find, unless they are closely related (e.g. same principle applied to more things). How would you like me to report my findings?

**Comment by nixbitcoin** [comment]
Exactly the same way!

**Comment by Kixunil** [comment]
So I created some [basic documentation of debian repository](https://github.com/Kixunil/cryptoanarchy-deb-repo-builder/tree/master/docs), which should make the review easier. I need to do some other things before I can review your repo, hopefully soon.

**Comment by nixbitcoin** [comment]
Collaboration is taking place in an ad-hoc fashion
