### ISSUE TITLE
Integrate Wasabi Daemon

### ISSUE THREAD

**Issue by nixbitcoin** [fort-nix/nix-bitcoin#181]
**Time Horizon**: Medium Term

**Description**: Package Wasabi's headless daemon and create a module that allows easy usage. This module should automatically create a "hot" mixing wallet and be able to send to an external xpub.

**Motivation**: Provide alternative CoinJoin implementation to JoinMarket for different use cases

**Implementation**: Examples
* @schulterklopfer https://github.com/schulterklopfer/wasabi_docker
* @pulpcattel https://github.com/PulpCattel/Spawn

**Comment by Kixunil** [comment]
Great! I want this too with some tool to remotely schedule mixes or have some rules like "whenever > X sats is on this xpub, mix them to reach anonset Y and send to XPUB2"

**Comment by nixbitcoin** [comment]
This is exactly what I had in mind. Maybe even use as BTCPayserver wallet so merchants can automatically mix to their coldstorage.

**Comment by Kixunil** [comment]
Is it already possible to use Wasabi as a backend? I believe it will require designing a new protocol around it. I gave a talk about it almost exactly a year ago (24 May :D). Will need to write it down I guess.

**Comment by nixbitcoin** [comment]
The wasabi daemon never seems to have gotten off the ground. JoinMarket is the better fit for nix-bitcoin and will stay our supported coinjoin solution.
