### ISSUE TITLE
nix-bitcoin should use acme for SSL certificates

### ISSUE THREAD

**Issue by reardencode** [fort-nix/nix-bitcoin#182]
I was able to get this working with the electrs package with the following in my configuration.nix:
```
        services.nginx.virtualHosts."satoshi.reardencode.com" = {
          forceSSL = true;
          enableACME = true;
        };
        services.nginx.appendConfig = ''
          stream {
            upstream electrs {
              server localhost:50001;
            }
            server {
              listen 50003 ssl;
              proxy_pass electrs;
              ssl_certificate /var/lib/acme/satoshi.reardencode.com/fullchain.pem;
              ssl_certificate_key /var/lib/acme/satoshi.reardencode.com/key.pem;
              ssl_trusted_certificate /var/lib/acme/satoshi.reardencode.com/full.pem;
            }
          }
        '';
      };
```
Obviously a bunch of those parts would need to be replaced with variables.

**Comment by nixbitcoin** [comment]
Our current setup creates self-signed certificates merely for the purpose of allowing Tor hidden service connections from Electrum Android, which forces the use of TLS. We are planning to deprecate the whole TLSProxy with Electrum 4.0.

Are you using ACME to create letsencrypt with which you can connect to electrs over clearnet?

**Comment by reardencode** [comment]
Ah, I see why you're using self-signed.

Seems like both modes should be supported. I'm not interested in using tor, but I know most users don't have existing publicly visible server infrastructure and domains.

--Brandon, sent by an android

-----Original Message-----

**Comment by nixbitcoin** [comment]
From the very beginning we wanted nix-bitcoin to protect its users privacy to the greatest extent possible. Among the measures to guarantee that was exclusively networking over Tor. Now that the project has also become interesting for businesses and infrastructure providers, I don't think we'll get around implementing an off-by-default clearnet switch.

Another interesting approach is better documenting a Wireguard routed setup, with a clearnet gateway on a public server. That way users and businesses can enjoy the speed and accessibility of clearnet, without revealing the IP address of their precious nix-bitcoin node.
