### ISSUE TITLE
nix-bitcoin should be directly importable from source archive

### ISSUE THREAD

**Issue by reardencode** [fort-nix/nix-bitcoin#184]
See https://gitlab.com/simple-nixos-mailserver/nixos-mailserver/-/blob/master/default.nix which can be imported as:
```
      imports = [
        (builtins.fetchTarball {
          url = https://gitlab.com/simple-nixos-mailserver/nixos-mailserver/-/archive/c2ee9f217ad35a2d614cd978786b8418805ee4e0/nixos-mailserver-c2ee9f217ad35a2d614cd978786b8418805ee4e0.tar.bz2;
          sha256 = "0wf1554x6qy524isz6zvadj4q7k8f24hqaj09fwaz64xsfgcxz5y";
        })
      ];
```
nix-bitcoin will be slightly more complicated because (currently) it includes packages in addition to modules, but the general idea should be the same.

**Comment by mmilata** [comment]
Might be also worth it to eventually package it as a nix flake: https://www.tweag.io/blog/2020-05-25-flakes/

**Comment by jonasnick** [comment]
Yes, nix-bitcoin should be importable into your existing nixos config. In any case we should document this better. What problems do you encounter when you try to import it same as `examples/shell.nix`? I haven't tried this out yet. In the meantime you can try to use a nix-bitcoin container as shown in `examples/deploy-container.sh`.

**Comment by jonasnick** [comment]
Nix flakes look cool, but it doesn'pt solve the problem of signed updates, so we'd still need some custom machinery in addition to the flake.

**Comment by erikarvstedt** [comment]
You can use flakes [(example)](https://github.com/fort-nix/nix-bitcoin/blob/master/examples/flakes/flake.nix) or do the following
```
imports = [
  "${builtins.fetchTarball {
    url = "https://github.com/fort-nix/nix-bitcoin//archive/v0.0.50.tar.gz";
    sha256 = "0mrrq51dwbanw2zh93dhbcjynr5avy4x7f0k7qb3vxgy7540mz1f";
  }}/modules/modules.nix"
];  
```
