### ISSUE TITLE
Integrate Samourai Dojo

### ISSUE THREAD

**Issue by reardencode** [fort-nix/nix-bitcoin#185]
Samourai Dojo is required for Samourai Wallet users to avoid using Samourai's backend servers. It would be great to see it supported along with electrs.

https://github.com/Samourai-Wallet/samourai-dojo/blob/develop/README.md

**Comment by nixbitcoin** [comment]
We originally considered implementing Dojo in https://github.com/fort-nix/nix-bitcoin/issues/32. I decided to first implement JoinMarket and Wasabi, because I personally use them. But I'm open to reviewing PR's for Dojo, since I know they also have a dedicated userbase.

**Comment by nixbitcoin** [comment]
Not on the roadmap for the base repo anymore
