### ISSUE TITLE
bitcoind RPC whitelist

### ISSUE THREAD

**Issue by nixbitcoin** [fort-nix/nix-bitcoin#191]
**Time Horizon:** Short Term

**Description:** Now that Bitcoin 0.20.0 is released we can utilize rpc whitelists to further lock down the bitcoind rpc server.

**Motivation:** clightning, lnd, liquid and electrs only need access to public bitcoind rpc calls.

**Implementation:** https://github.com/bitcoin/bitcoin/pull/12763

**Comment by Kixunil** [comment]
FYI, the [list of methods](https://github.com/Kixunil/btc-rpc-proxy/blob/master/btc_rpc_proxy.toml#L7) verified to work with:

* lnd
* electrs

`getpeerinfo` is needed for NBXplorer due to https://github.com/MetacoSA/NBitcoin/issues/864
