### ISSUE TITLE
Integrate BTCPayserver

### ISSUE THREAD

**Issue by nixbitcoin** [fort-nix/nix-bitcoin#196]
**Time Horizon:** Mid Term

**Description:** Integrate BTCPayserver pkg and module.

**Motivation:** BTCPayserver seems to develop into the default solution for accepting Bitcoin payments.

**Implementation:** Create BTCPayserver pkg and make it easy to use as a module. Clearnet and Tor.

**Comment by Kixunil** [comment]
FYI, you probably want NBXplorer as a separate package. (A separate issue for that?)

**Comment by jb55** [comment]
nbxplorer is packaged in #179, since its a requirement to run btcpayserver

**Comment by nixbitcoin** [comment]
Closed with https://github.com/fort-nix/nix-bitcoin/pull/221
