### ISSUE TITLE
Bash issue in deploy-nixops.sh

### ISSUE THREAD

**Issue by gotcha** [fort-nix/nix-bitcoin#211]
When running `deploy-nixops.sh` on MacOS 10.13.6 ``GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)`` I get

    ./deploy-nixops.sh: line 11: conditional binary operator expected

**Comment by jonasnick** [comment]
I think the problem is that bash 3 does not support "-v". You can try running the script after entering `nix-shell` in the examples directory.

**Comment by erikarvstedt** [comment]
@jonasnick's comment should fix this.
