### ISSUE TITLE
AppArmor not starting causing configuration activation to fail

### ISSUE THREAD

**Issue by hard-money** [fort-nix/nix-bitcoin#214]
Hi,

I'm installing nix-bitcoin on a APU2, following the steps in the install.md for own hardware deployment.

During the deployment, I get the following error:
```
_bitcoin-node> Jul 28 01:12:25 nix-bitcoin systemd[1]: Starting apparmor.service...
bitcoin-node> Jul 28 01:12:25 nix-bitcoin apparmor_parser[1608]: Warning from stdin (line 1): config file '/etc/apparmor/parser.conf' not found
bitcoin-node> Jul 28 01:12:25 nix-bitcoin apparmor_parser[1608]: Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)
bitcoin-node> Jul 28 01:12:25 nix-bitcoin apparmor_parser[1608]: Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
bitcoin-node> Jul 28 01:12:25 nix-bitcoin apparmor_parser[1608]: Use --subdomainfs to override.
bitcoin-node> Jul 28 01:12:25 nix-bitcoin systemd[1]: apparmor.service: Main process exited, code=exited, status=1/FAILURE
bitcoin-node> Jul 28 01:12:25 nix-bitcoin systemd[1]: apparmor.service: Failed with result 'exit-code'.
bitcoin-node> Jul 28 01:12:25 nix-bitcoin systemd[1]: Failed to start apparmor.service.
bitcoin-node> error: Traceback (most recent call last):
  File "/nix/store/s2h2sckj6fzjmw2czb12kdcxihxs0fw9-nixops-1.8pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 746, in worker
    raise Exception("unable to activate new configuration (exit code {})".format(res))
Exception: unable to activate new configuration (exit code 4)_
```
It seemed to have changed my root password and I don't know the password for the operator user. Luckily, I set up a ssh key authentication and was able to login using that and changed the passwd for operator.

While my bitcoin related apps seem to be running, I feel a bit uneasy that my configuration did not fully activate. Any ideas on how to resolve this AppArmor issue and force a configuration activation again?

Thanks!

**Comment by nixbitcoin** [comment]
I got the exact same issue when first deploying to my beautiful APU, however, after a restart AppArmor seemed to run fine. I think the kernel needs to reboot with param `security=apparmor` to fix this issue. You can check `/proc/cmdline` for the param.

The root password probably didn't change but `PermitRootLogin prohibit-password` is prohibiting you from logging in via ssh with the root password, which is a good thing. You can check `/etc/ssh/sshd_config` for that configuration line.

**Comment by hard-money** [comment]
Thanks nixbitcoin, rebooting did fix the issue. The security=apparmor was set in grub w/o my intervention.

Is it safe for me to try to redeploy the configuration to my apu2? Using `nixops deploy -d bitcoin-node`

My "operator" user does not have the ssh keys set up by nixops.

**Comment by nixbitcoin** [comment]
Yes it is safe to redeploy

Nixops ssh keys for the operator user should have been set up automatically. Did you try entering the `nix-shell` and running `nixops ssh operator@bitcoin-node`?

**Comment by hard-money** [comment]
I was not able to connect to my node using `nixops ssh operator@bitcoin-node`. Could it be that the `ssh-keygen` command is not executed due to my apparmor service not starting? Since this isn't the original issue, I will close this issue.

Thanks for the support nixbitcoin!

**Comment by nixbitcoin** [comment]
Have you been able to resolve the `nixops ssh operator@bitcoin-node` issue? If not, please open a new issue so we can fix it together.

**Comment by hard-money** [comment]
Just noticed this now. I was able to connect to my machine using `nixops ssh operator@bitcoin-node`. Pretty sure it was a newbie's mistake.

**Comment by galderz** [comment]
I've just had the same issue (see https://github.com/fort-nix/nix-bitcoin/issues/278). I've rebooted the machine but I don't know what the status of things are, nor can I SSH into the machine with `nixops ssh operator@bitcoin-node`, it asks me for the password.
