### ISSUE TITLE
Add Tor v3 Client Authorization

### ISSUE THREAD

**Issue by 05nelsonm** [fort-nix/nix-bitcoin#232]
Implement way of generating the Base32 encoded pub/priv x25519 key pair for enabling Tor v3 Client Authorization for Hidden Services.

https://community.torproject.org/onion-services/advanced/client-auth/

**Comment by nixbitcoin** [comment]
I like the idea, this could give us an additional layer of security for accessing services remotely. Which service, specifically, do you need this for?

**Comment by 05nelsonm** [comment]
For now, just Bitcoin Core, but in the future I will be supporting from Android:

Join Market
Ride The Lightning
Umbrel
Esplora

**Comment by 05nelsonm** [comment]
On another note, I'm writing the command line tools (Bash) for generating a QR code to use for importing the connection information into the App.

The current schema for the string value is:

```
<my app's name which is a surprise ;-D>connect://<onion-address.onion>:<connection port>?v3authprivkey=<v3-client-auth-private-key>?service=<type-of-service-being-connected-to>?username=<u-name>?password=<p-word>?cert=<tls-cert-if-applicable>
```

My plans for this are that the user runs

 - `$ git clone <repo info> && cd <repo-name>`
 - `$ ./<surprise>_connect wizard`

and it walks them through everything (Creating Hidden Services, generating Client Auth Keys, generating QR Codes, etc.). There's also an additional option instead of the wizard for importing the information directly via setting of flags to generate the QR code.

Currently I am using OpenSSL to password encrypt the string value before displaying the content to terminal (which gets automatically decrypted in the application when imported).

Is OpenSSL a package that will be available from NixBitcoin to achieve this?

**Comment by jonasnick** [comment]
> Is OpenSSL a package that will be available from NixBitcoin to achieve this?

Yes, it' already used for some things (generating certs etc).

**Comment by nixbitcoin** [comment]
Closed because of lack of momentum/unlikely this will ever serve a viable purpose
