### ISSUE TITLE
Declarative Installation Fails

### ISSUE THREAD

**Issue by xwvvvvwx** [fort-nix/nix-bitcoin#241]
Hi, I am attempting to use `nix-bitcoin` from my existing nixos configuration. I have defined the following module, but I get an error:

```
error: attribute 'nix-bitcoin' missing, at /nix/store/rvkgx88xsykyjb2lqk5wgl9pxq655zlw-nix-bitcoin-43cac9d35e94f58c615aa9bd71e46310ddf17ab8/modules/secrets/generate-secrets.nix:23:9
```

What am I doing wrong?

## Config

```nix
{ config, pkgs, lib, ... }:
let
  nix-bitcoin = fetchGit rec {
    url = https://github.com/fort-nix/nix-bitcoin.git;
    ref = "master";
    rev = "43cac9d35e94f58c615aa9bd71e46310ddf17ab8";
    name = "nix-bitcoin-${rev}";
  };

  containerName = "nix-bitcoin"; # container name length is limited to 11 chars
  localAddress = "10.250.0.2"; # container address
  hostAddress = "10.250.0.1";
in {
  systemd.tmpfiles.rules = [
    "d /hdd/bitcoin - root root - -"
    "d /hdd/bitcoin/bitcoind - root root - -"
  ];
  containers.${containerName} = {
    bindMounts."/bitcoin" = {
      hostPath = "/hdd/bitcoin";
      isReadOnly = false;
    };

    autoStart = true;

    privateNetwork = true;
    inherit localAddress hostAddress;

    config = { pkgs, config, lib, ... }: {
      imports = [
        "${nix-bitcoin}/modules/presets/secure-node.nix"
        "${nix-bitcoin}/modules/secrets/generate-secrets.nix"
      ];

      # Speed up evaluation
      documentation.nixos.enable = false;

      services.bitcoind = {
        enable = true;
        package = pkgs.bitcoind;
        dataDir = "/bitcoin/bitcoind";
      };

      networking.hostName = "nix-bitcoin";
      time.timeZone = "UTC";
    };
  };

  # Allow WAN access
  systemd.services."container@${containerName}" = {
    preStart = "${pkgs.iptables}/bin/iptables -w -t nat -A POSTROUTING -s ${localAddress} -j MASQUERADE";
    # Delete rule
    postStop = "${pkgs.iptables}/bin/iptables -w -t nat -D POSTROUTING -s ${localAddress} -j MASQUERADE || true";
  };
}
```

**Comment by erikarvstedt** [comment]
Your config builds and runs fine in a VM: https://gist.github.com/206130228e19d21f693c32a81e6ce77b
(Note that the container host needs  `boot.kernel.sysctl."net.ipv4.ip_forward" = true;` set to enable WAN.)
Could you provide a self-contained example to reproduce the bug?

**Comment by xwvvvvwx** [comment]
@erikarvstedt I can reproduce the issue using your script. I'm running `nixos-unstable` and using `nix` 2.3.7.

I cleaned up the example a bit, and pinned `nixpkgs` to `unstable` in the vm, can you try this example and see if it reproduces for you: https://ipfs.io/ipfs/QmfSxmEYAxKLVAQd5AcnPhRPiGA8tSFws75avmWpb2seC2/vm.html

**Comment by erikarvstedt** [comment]
This was broken by https://github.com/NixOS/nixpkgs/pull/85570, I've proposed a fix [here](https://github.com/NixOS/nixpkgs/pull/98655).
There was also another, unstable-only [issue](https://github.com/fort-nix/nix-bitcoin/pull/242).

Here's a [workaround](https://gist.github.com/fcd3b8298983298b4ddfc161f585db79)

**Comment by xwvvvvwx** [comment]
The container boots with the workaround. Thanks!!!!
