### ISSUE TITLE
CI discussion

### ISSUE THREAD

**Issue by jonasnick** [fort-nix/nix-bitcoin#260]
From #258 

> To clarify this, I've added a debug helper and re-run the travis build, but it's still stalling, like in the last few days.
> @jonasnick, should I investigate a migration to Github Actions?

I'd be open to switching to a different CI system. We need to switch from travis.org to travis.com anyway because apparently they're moving over resources to travis.com. But travis.com [has unacceptable permissions](https://github.com/bitcoin/bitcoin/issues/17802#issuecomment-718857563). Apparently [github actions](https://github.com/bitcoin/bitcoin/pull/18031) had similar issues - not sure if that's still the case or what they're specifically referring to. @erikarvstedt Do you have experience with Github Actions? I haven't read up on this really, but short google search revealed that generally it seems to be preferred over travis.

**Comment by jonasnick** [comment]
From https://github.com/bitcoin/bitcoin/issues/17802#issuecomment-724684116
> Travis for open source is effectively shutting down, so I don't think this is an option. See also: [...]

More on Github Actions https://github.com/bitcoin/bitcoin/issues/17803#issuecomment-725551444

**Comment by nixbitcoin** [comment]
We're [now using](https://github.com/fort-nix/nix-bitcoin/pull/276) CirrusCI
