### ISSUE TITLE
test-compat and test-conf errors

### ISSUE THREAD

**Issue by galderz** [fort-nix/nix-bitcoin#262]
Trying to install nix-bitcoin packages from fedora 32 box, and got 2 errors on `nix-shell` execution:

```
ERROR: test-compat - missing test plan
...
ERROR: test-conf - missing test plan
```

See longer output [here](https://gist.github.com/galderz/a102f854d8969a9eb92e7907b125dd7f).

Any ideas how to fix this?

**Comment by erikarvstedt** [comment]
Which command did you run?
What is your fedora version?

**Comment by erikarvstedt** [comment]
Does `./deploy-qemu-vm.sh` (see examples section in the README) work for you?

**Comment by galderz** [comment]
> Which command did you run?

`nix-shell` as indicated in step 2 [here](https://github.com/fort-nix/nix-bitcoin/blob/master/docs/install.md#3-setup-deployment-directory).

> What is your fedora version?

fedora 32.

I've not tried `./deploy-qemu-vm.sh`

**Comment by galderz** [comment]
I had wrongly installed single-user nix, which led to this kind of issues. I found the hint in [this issue](https://github.com/NixOS/nixpkgs/issues/96715). Switched to multi-user and nix-shell starts fine now.
