### ISSUE TITLE
Deployment Error: Failed to create initrd secrets

### ISSUE THREAD

**Issue by hard-money** [fort-nix/nix-bitcoin#268]
Hi,

I can't seem to activate my configuration for nix-bitcoin-0.0.23. 

I'm getting the following error:
`bitcoin-node> failed to create initrd secrets: No such file or directory`
`bitcoin-node> error: Traceback (most recent call last):`
`  File "/nix/store/cp7xs91v1nmcn8bgccy0k5z4ivrxvl3d-nixops-1.8pre0_abcdef/lib/python2.7/site-packages/nixops/deployment.py", line 746, in worker`
`    raise Exception("unable to activate new configuration (exit code {})".format(res))
Exception: unable to activate new configuration (exit code 1)`

**Comment by nixbitcoin** [comment]
Might be related to https://github.com/NixOS/nixpkgs/issues/100799. @erikarvstedt what do you think?

**Comment by hard-money** [comment]
The following segfault is causing the activation to fail:

`nix-bitcoin kernel: append-initrd-s[26998]: segfault at 6b1f00000008 ip 00006b1f1e599018 sp 00007a75345f1dd0 error 4 in ld-2.30.so[6b1f1e58b000+1e000]`

This was the command line that caused the dump based on the coredump info:
`/nix/store/hrpvwkjz04s9i4nmli843hyw9z4pwhww-bash-4.4-p23/bin/bash -e /nix/var/nix/profiles/system-17-link/append-initrd-secrets /boot/kernels/initrd-secrets.8VzQyOBG`

In case this helps, I'm running nix-bitcoin on an apu2 with apparmor enabled.

**Comment by nixbitcoin** [comment]
@erikarvstedt Can we pull in `nixos/modules/config/malloc.nix` from https://github.com/NixOS/nixpkgs/pull/104052?

**Comment by erikarvstedt** [comment]
> Can we pull in ...

Sure, but I'd prefer a backport. Just open a nixpkgs PR and I'll review it.

I also think that we should disable the hardened profile by default in `configuration.nix`. Its creator [states](https://github.com/NixOS/nixpkgs/issues/100799#issuecomment-728935064) that it's more of an overview of possible hardening measures and that it was "never intended for normal deployments".

**Comment by hard-money** [comment]
I'm trying to activate a configuration with the hardened profile commented out on nix-bitcoin-release = "nix-bitcoin-0.0.21" (last version before nixpkgs 20.09), but I getting the same activation error when I try to deploy.

Is there any steps I can follow to activate my configuration w/o the hardened profile?

**Comment by nixbitcoin** [comment]
What system are you deploying from? The box itself?

**Comment by hard-money** [comment]
I'm deploying from a remote computer (debian 10) onto my apu2 running nixos. 

I could also try to ssh into my box to activate. I'm just not very familiar with Nix and its best practice.

**Comment by nixbitcoin** [comment]
Try sshing into your box and deleting `/etc/ld-nix.so.preload`. Then redeploying without the hardened profile.

**Comment by nixbitcoin** [comment]
> Sure, but I'd prefer a backport. Just open a nixpkgs PR and I'll review it.

https://github.com/NixOS/nixpkgs/pull/106842

**Comment by nixbitcoin** [comment]
> > Can we pull in ...
> 
> Sure, but I'd prefer a backport. Just open a nixpkgs PR and I'll review it.
> 
> I also think that we should disable the hardened profile by default in `configuration.nix`. Its creator [states](https://github.com/NixOS/nixpkgs/issues/100799#issuecomment-728935064) that it's more of an overview of possible hardening measures and that it was "never intended for normal deployments".

**Comment by hard-money** [comment]
Thanks @nixbitcoin! That worked for me. Feel free to close my issue.

**Comment by nixbitcoin** [comment]
I'll let you know when we get the fix merged upstream and you can reenable the hardened profile. Glad to help :heart:

**Comment by galderz** [comment]
I had the same issue too, and following the tip [here](https://github.com/fort-nix/nix-bitcoin/issues/268#issuecomment-744037221) worked.
