### ISSUE TITLE
Demo installation seems down

### ISSUE THREAD

**Issue by danielabrozzoni** [fort-nix/nix-bitcoin#269]
From the README:
```
A demo installation is running at http://6tr4dg3f2oa7slotdjp4syvnzzcry2lqqlcvqkfxdavxo6jsuxwqpxad.onion.
```

but opening that on Tor-Browser shows:

![Problem Loading Onionsite - Tor Browser_028](https://user-images.githubusercontent.com/25042473/100126710-9a097480-2e7e-11eb-9c92-fa8880fd0109.png)

**Comment by nixbitcoin** [comment]
We need to renew the demo installation anyway with our own BTCPayServer instance.
