### ISSUE TITLE
Update electrs version

### ISSUE THREAD

**Issue by Kixunil** [fort-nix/nix-bitcoin#274]
I've tried to check if you've updated `electrs` version to 0.8.6 and it seems you didn't, close & ignore if you did.

The recent version of `electrs` is a quite important update as it fixes communication with Electrum (it was problematic before and completely broken for Electrum 4.0.5) and potential security vulnerability.
It also brings few other fixes and improvements of reliability etc.
We recommend you update it as soon as possible.

The new version is fully backwards-compatible. You only need to replace the binary without changing anything else. However as you're packaging system, I suggest you look at possible improvements available thanks to the recent changes:

* Dynamic linking is now supported and documented - it is also deterministic
* Cross compilation is supported and documented, however it was only tested for arm64 so far, armhf failed

The documentation can be found in see `docs/usage.md`.

I've noticed you had some trouble before (#143 ), I guess these changes will help you avoid those issues. Feel free to ask me if you need help with something Rust/build/electrs related.

**Comment by erikarvstedt** [comment]
Thanks! The previous build issues were only related to a manual build without cargo. The cargo build works fine.

**Comment by Kixunil** [comment]
Yeah, using Rust without cargo is like trying to build the Linux kernel without Makefile. :)
