### ISSUE TITLE
Support btcpayserver in recurring-donations

### ISSUE THREAD

**Issue by jonasnick** [fort-nix/nix-bitcoin#294]
This would be nice because that would allow sending donations to a large part of https://bitcoindevlist.com/ and to our own https://nixbitcoin.org.

With the help of @kukks I already tried to write a simple script that fetches a lightning invoice from btcpayserver, but gave up when I realized that it's not that straightforward. In any case, here's how far I got last time I tried: https://gist.github.com/jonasnick/1b2dbe3a62881cf6c9941a98be1b51a2

**Comment by Kukks** [comment]
> This would be nice because that would allow sending donations to a large part of https://bitcoindevlist.com/ and to our own https://nixbitcoin.org.
> 
> With the help of @Kukks I already tried to write a simple script that fetches a lightning invoice from btcpayserver, but gave up when I realized that it's not that straightforward. In any case, here's how far I got last time I tried: https://gist.github.com/jonasnick/1b2dbe3a62881cf6c9941a98be1b51a2

It all depends on how a user exposes their donation page. There are currently 2 main ways right now:
* Pay Button - at the endpoint of `${BASEURL}/api/v1/invoices`
* Apps (Crowdfund or point of sale)  - at the endpoint of https://btcpay.kukks.org/apps/$APPID/{pos | crowdfund}

Unfortunately, it's not that straightforward as you need it to be

**Comment by nixbitcoin** [comment]
Recurring donations module has been removed in https://github.com/fort-nix/nix-bitcoin/pull/425 in favor of bolt12 and/or LNURL in the future
