### ISSUE TITLE
nix-bitcoin-webindex requires nanopos.

### ISSUE THREAD

**Issue by whoisgit** [fort-nix/nix-bitcoin#298]
Hello,
  I follow the install.md  , "4. Deploy with nixops in nix-shell
nixops deploy -d bitcoin-node",  always show me: Failed assertions:
- nix-bitcoin-webindex requires nanopos.
 I using debian9 install nix-bitcoin,  How to fix that?

**Comment by erikarvstedt** [comment]
Please remove `services.nix-bitcoin-webindex.enable = true` from your `configuration.nix`.

**Comment by whoisgit** [comment]
> Please remove `services.nix-bitcoin-webindex.enable = true` from your `configuration.nix`.

thx for your reply. when I remove the label, that's works.
