### ISSUE TITLE
Add helper for publishing bitcoin.pdf

### ISSUE THREAD

**Issue by Kixunil** [fort-nix/nix-bitcoin#305]
This feature will make whitepaper more available.
Similar feature was already implemented in Debian repository and is being worked on in BTCPayServer.

**Comment by erikarvstedt** [comment]
Concept ACK, but since we currently don't have a public webinteface I think this is out of scope for now.
Maybe @nixbitcoin could host it on his [node](https://nixbitcoin.org/).

**Comment by Kixunil** [comment]
Feel free to steal any of my web interface ideas:

* [Overview of `selfhost`](https://github.com/Kixunil/cryptoanarchy-deb-repo-builder/blob/master/docs/user-level.md#selfhost)
* [`selfhost` tools source code](https://github.com/Kixunil/cryptoanarchy-deb-repo-builder/tree/master/selfhost) - check `nginx` first
* [how trivial it is to integrate apps](https://github.com/Kixunil/cryptoanarchy-deb-repo-builder/blob/master/pkg_specs/thunderhub-system-%40variant.sps#L113)
* [`selfhost-dashboard` with pluggable apps](https://github.com/Kixunil/selfhost-dashboard) - the last three options in the example above connect ThunderHub with `seldhost-dashboard` along with [a script to provide SSO](https://github.com/Kixunil/cryptoanarchy-deb-repo-builder/blob/master/thunderhub/selfhost-dashboard/entry_points/open)

**Comment by jonasnick** [comment]
You can easily distribute the whitepaper by running any of the torrent implementations already available in the nixpkgs without adding new machinery to nix-bitcoin. Moreover, nix-bitcoin's mission isn't to host PDFs and the whitepaper is widely available (now).

**Comment by Kixunil** [comment]
@jonasnick sure, it was a half-joke. :) Perhaps ThunderHub and stuff would be more interesting though.

**Comment by jonasnick** [comment]
There's nothing wrong with hosting it on nixbitcoin.org. Closing this for now. Thanks nonetheless for the pointers @Kixunil.
