### ISSUE TITLE
Feature request: Blockstream Satellite

### ISSUE THREAD

**Issue by MrPaz** [fort-nix/nix-bitcoin#318]
I've been hoping one of the full node OS's will implement Blockstream satellite.  Since I believe nix-bitcoin is created by a Blockstream engineer, maybe this will be the project to get it done.  An easy to setup, always on pi node with Blocksat already installed would be awesome and could be a catalyst for more people to run a satellite node.

**Comment by nixbitcoin** [comment]
Duplicate of https://github.com/fort-nix/nix-bitcoin/issues/180

This is still very much on the roadmap, just need to get the necessary hardware and sit down to do it.
