### ISSUE TITLE
Package ‘libvirt-5.9.0’ is marked as insecure, refusing to evaluate.

### ISSUE THREAD

**Issue by nixbitcoin** [fort-nix/nix-bitcoin#323]
Steps to reproduce

1. Execute `./deploy-qemu.sh` from master

**Comment by erikarvstedt** [comment]
I can't reproduce this from NixOS. Are you running Arch?
Does the following work when run from the repo root?
```
export NIX_PATH=nixpkgs=$(nix eval --raw -f "pkgs/nixpkgs-pinned.nix" nixpkgs):nix-bitcoin=$(realpath ".")
nix-build --no-out-link - <<EOF
(import <nixpkgs/nixos> {
  configuration = {
    imports = [
      <nix-bitcoin/examples/configuration.nix>
      <nix-bitcoin/modules/secrets/generate-secrets.nix>
    ];
    virtualisation.graphics = false;
    services.mingetty.autologinUser = "root";
  };
}).vm
EOF
```

**Comment by jonasnick** [comment]
I can reproduce the problem. It doesn't have anything to do with qemu per se but with nixops19_09 (which is built when invoking the example nix-shell in deploy-qemu.sh).

```
export NIX_PATH=nixpkgs=$(nix eval --raw -f "pkgs/nixpkgs-pinned.nix" nixpkgs)
nix-build --no-out-link pkgs -A nixops19_09
```

**Comment by nixbitcoin** [comment]
> I can't reproduce this on NixOS. Are you running Arch?
> Does the following script succeed when run from the repo root?
> 
> ```shell
> export NIX_PATH=nixpkgs=$(nix eval --raw -f "pkgs/nixpkgs-pinned.nix" nixpkgs):nix-bitcoin=$(realpath ".")
> nix-build --no-out-link - <<EOF
> (import <nixpkgs/nixos> {
>   configuration = {
>     imports = [
>       <nix-bitcoin/examples/configuration.nix>
>       <nix-bitcoin/modules/secrets/generate-secrets.nix>
>     ];
>     virtualisation.graphics = false;
>     services.mingetty.autologinUser = "root";
>   };
> }).vm
> EOF
> ```

This script does succeed

**Comment by mmilata** [comment]
Would this be a good time to update to newer nixops than what's in 19.09? Not sure whether it has working libvirtd backend but willing to look into it.

**Comment by galderz** [comment]
I'm seeing this. How do I permanently fix this?

**Comment by galderz** [comment]
I see this when doing `nix-shell`

**Comment by jonasnick** [comment]
@galderz this is fixed with the latest release. So you should just have to run `fetch-release > nix-bitcoin-release.nix` in your nix shell and restart the shell.
