### ISSUE TITLE
Why change the default assumevalid?

### ISSUE THREAD

**Issue by tyrion** [fort-nix/nix-bitcoin#328]
Forgive me if this does not make sense, I am not a bitcoin expert.
I am trying to understand what is the purpose of changing the default `assumevalid` of bitcoind as done in #132 .
As far as I understand the default [`assumevalid` is updated with every release of bitcoind][1], so there shouldn't be the need to change it in nix-bitcoin.

[1]: https://bitcoin.stackexchange.com/a/88666/109163

**Comment by jonasnick** [comment]
Yeah this can be removed - especially if we fail to update this. I added this mostly for demonstration purposes.

**Comment by tyrion** [comment]
Thank you for the clarification. Feel free to close this issue as you see fit. :)

**Comment by jonasnick** [comment]
We can leave it open to track removal of assumevalid.
