### ISSUE TITLE
Update banlist

### ISSUE THREAD

**Issue by nixbitcoin** [fort-nix/nix-bitcoin#338]
Tried reaching @gmaxwell by email to get an updated banlist, but no response. Anybody else no how to contact him?

**Comment by nixbitcoin** [comment]
I messaged @gmaxwell one more time. I don't expect a response. We should look for alternatives or just leave it as is.

**Comment by seberm** [comment]
Shouldn't we close this issue? The bitcoin banlist was removed in #512 . Or is there a plan to use some alternative?

Thanks!

**Comment by erikarvstedt** [comment]
@seberm, yes, this can be closed Thanks!
