### ISSUE TITLE
Change `0.0.41` release notes

### ISSUE THREAD

**Issue by erikarvstedt** [fort-nix/nix-bitcoin#340]
Is it okay if I add this change to the [release notes](https://github.com/fort-nix/nix-bitcoin/releases/tag/v0.0.41)?
```
Therefore, it is generally advised to migrate to krops.
-> 
Therefore, it is generally advised to switch to an official version of NixOps or to migrate to krops.
``` 
NixOps is still a supported deployment method and it's the better option for users that want to build their system locally.

**Comment by jonasnick** [comment]
Right, I changed it.
