### ISSUE TITLE
Update to NixOS 21.05

### ISSUE THREAD

**Issue by jonasnick** [fort-nix/nix-bitcoin#364]
Release notes: https://nixos.org/manual/nixos/stable/release-notes.html#sec-release-21.05

**Comment by erikarvstedt** [comment]
Implementation started in https://github.com/fort-nix/nix-bitcoin/pull/344, I'll finish this up over the next days.

**Comment by jonasnick** [comment]
Ah I forgot about your PR. Great.

**Comment by nixbitcoin** [comment]
Are you still working on this or should I take over?

**Comment by jonasnick** [comment]
PR #374 was merged.
