### ISSUE TITLE
Simplify lnd-create-wallet

### ISSUE THREAD

**Issue by jonasnick** [fort-nix/nix-bitcoin#377]
- [x] ~Instead of checking that wallet.dat exists, we can check if the state endpoint returns `NO_WALLET`.~ (EDIT: more complicated than just checking whether a file exists)
- [x] Instead of unlocking with the unlockwallet endpoint, we can set lnd's `wallet-unlock-password-file` flag. This would also require the `wallet-unlock-allow-create` flag because otherwise lnd fails if there is no wallet.
  By the way, the [commit that introduces this flag](https://github.com/lightningnetwork/lnd/commit/6ca38bc8150fcd299c633c4f44e187b486c76953) mentions a security issue where an unauthenticated attacker can inject a seed using the `initwallet` endpoint. But that's already an issue today (if netns isn't enabled). Afaik `initwallet` can be turned off after the [lndinit tool](https://github.com/lightningnetwork/lnd/pull/5150) is merged.
- [ ] Use [lndinit tool](https://github.com/lightningnetwork/lnd/pull/5150)  to create the wallet.

**Comment by Kixunil** [comment]
>  that's already an issue today

Yes

>  Afaik `initwallet` can be turned off after the lndinit tool is merged.

Correct, that is the intended way to fix the vulnerability.

I wrote [this script](https://github.com/debian-cryptoanarchy/cryptoanarchy-deb-repo-builder/blob/master/lnd/auto_unlock.sh) which will be rewritten once `lndinit` is available, feel free to get inspiration from there. :) Note that 0.14 will have [systemd integration](https://github.com/lightningnetwork/lnd/pull/5536) which should make things significantly easier.

**Comment by jonasnick** [comment]
lndinit is now published in a separate repo: https://github.com/lightninglabs/lndinit

**Comment by erikarvstedt** [comment]
I've implemented lndinit-based wallet creation in [this branch](https://github.com/erikarvstedt/nix-bitcoin/commits/lnd-lndinit).

Overall, I think using `lndinit` brings no net benefits:
`lndinit` is an extra package and adds a ~60s build to the initial setup and a 42MiB binary to the system closure.
It slows down initial service startup (relevant for quick container tests) by 0.5 s (+17%).
Code-wise, it slightly simplifies service initialization, but adds an extra package that has to be maintained.
The existing REST-based wallet creation method is perfectly reliable and seems like the better choice for now.

**Comment by erikarvstedt** [comment]
In the above verdict I forgot that `lndinit` fixes a security bug (see jonasnick's initial post). In light of this, it's obvious that we should switch to lndinit.
