### ISSUE TITLE
Heads up: upcoming changes to electrs

### ISSUE THREAD

**Issue by Kixunil** [fort-nix/nix-bitcoin#392]
The upcoming version of electrs will have two major changes: it will use p2p instead of reading blk files or Json and it will change database format (likely causing automatic reindex unless disabled).

If you need some other change to ensure upgrades of your packages are smooth please let us know or make a PR if the change is large.

Check https://github.com/romanz/electrs/pull/487 which proposes hopefully clear documentation on this (LMK if something is not clear).

**Comment by prusnak** [comment]
Thanks for the heads-up. My WIP branch with electrs-0.9.0-rc1 is here: https://github.com/prusnak/nixpkgs/tree/electrs

**Comment by prusnak** [comment]
I am preparing the changes for the upcoming 0.9.0 release in here: https://github.com/prusnak/nixpkgs/tree/electrs-next

**Comment by erikarvstedt** [comment]
Thanks, @Kixunil! I'll prepare the nix-bitcoin update.

**Comment by prusnak** [comment]
> Thanks, @Kixunil! I'll prepare the nix-bitcoin update.

Already in https://github.com/NixOS/nixpkgs/pull/140018

**Comment by prusnak** [comment]
PR https://github.com/NixOS/nixpkgs/pull/140018 has been merged and electrs 0.9.0 is in nixpkgs master now

**Comment by erikarvstedt** [comment]
It will be added as soon as it hits `nixpkgs-unstable`.

**Comment by erikarvstedt** [comment]
Implemented in https://github.com/fort-nix/nix-bitcoin/pull/404.
