### ISSUE TITLE
Include Mempool block explorer

### ISSUE THREAD

**Issue by prusnak** [fort-nix/nix-bitcoin#394]
https://github.com/mempool/mempool

We have all dependencies already packaged in nixpkgs - see https://github.com/mempool/mempool#dependencies

**Comment by nixbitcoin** [comment]
What's the use-case of a self-hosted block explorer?

**Comment by prusnak** [comment]
> What's the use-case of a self-hosted block explorer?

Not needing to use a hosted block explorer.

**Comment by jonasnick** [comment]
Like @nixbitcoin, I would like to know how and why exactly people use block explorers. Doesn't your wallet usually show the transaction details?

**Comment by mmilata** [comment]
Yes.

**Comment by nixbitcoin** [comment]
This is actively being worked on under https://github.com/nixbitcoin/nix-bitcoin/commits/mempool-nb

**Comment by erikarvstedt** [comment]
@prusnak, the PR is in an early draft state, so I'd recommend to wait a bit.

**Comment by seberm** [comment]
@erikarvstedt @jonasnick I believe this issue can be closed.

**Comment by jonasnick** [comment]
Yes, thanks @seberm.
