### ISSUE TITLE
Possible to use nix-bitcoin to run bitcoin services on NixOS?

### ISSUE THREAD

**Issue by casey** [fort-nix/nix-bitcoin#395]
I have a nixos server that I configure with `/etc/nixos/configuration.nix`. I would like to run an LND node, but LND isn't yet packaged in nixpkgs, nor configurable in nixos. I was hoping to use nix-bitcoin to run LND, but was unable to figure out how to integrate the configuration into my `/etc/nixos/configuration.nix`. Is this possible, and is there documentation for it? Thank you!

**Comment by erikarvstedt** [comment]
Yes, nix-bitcoin has explicit support for integration into existing configs.
We have a `deploy-container-minimal.sh` [example](https://github.com/fort-nix/nix-bitcoin/tree/master/examples) to cover this use case. I've now improved this by [adding](https://github.com/fort-nix/nix-bitcoin/pull/396) a [standalone-configuration.nix](https://github.com/fort-nix/nix-bitcoin/blob/2f2d0a2203edf70dde58d4bfb8b433558ff7a0f4/examples/standalone-configuration.nix) example file which you can directly copy to your system config.

**Comment by prusnak** [comment]
> LND isn't yet packaged in nixpkgs, nor configurable in nixos

LND is packaged in nixpkgs - see https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/blockchains/lnd/default.nix

However, I see there is indeed no module similar to https://github.com/fort-nix/nix-bitcoin/blob/master/modules/lnd.nix in nixpkgs.

**Comment by jonasnick** [comment]
Added more importable config and documentation in #396.
