### ISSUE TITLE
Add PyBLOCK.

### ISSUE THREAD

**Issue by SatoshiNakamotoBitcoin** [fort-nix/nix-bitcoin#422]
a@A:~> git clone https://github.com/curly60e/pyblock.git
a@A:~> cd pyblock
a@A:~> pip3 install -r requirements.txt
a@A:~> sudo apt install hexyl
a@A:~> python3 PyBlock.py

https://curly60e.github.io/pyblock/

**Comment by nixbitcoin** [comment]
IMO not enough need to warrant the creation and maintenance effort in nix-bitcoin

**Comment by prusnak** [comment]
Let's close this then?
