### ISSUE TITLE
lnd: not using `tor.streamisolation`

### ISSUE THREAD

**Issue by nixbitcoin** [fort-nix/nix-bitcoin#442]
Is this an issue?

**Comment by erikarvstedt** [comment]
See [here](https://github.com/lightningnetwork/lnd/discussions/5783).
Summary:
`IsolateDestAddr`, which is enabled by default for the NixOS Tor SOCKS proxy at port 9050, is sufficient. 
`tor.streamisolation` brings no extra benefits.

**Comment by nixbitcoin** [comment]
Ah, missed that. Thanks.
