### ISSUE TITLE
add cypherpunkpay

### ISSUE THREAD

**Issue by prusnak** [fort-nix/nix-bitcoin#453]
A lightweight alternative to BtcPayServer written in Python: https://cypherpunkpay.org

Nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/159879

**Comment by nixbitcoin** [comment]
IMO we should stick with btcpayserver in the nix-bitcoin core distribution because it is the most widely used solution for self-hosted BTC payment processing. Open to review PRs or custom modules outside nix-bitcoin though.

**Comment by prusnak** [comment]
Fair enough. Let's close then.

**Comment by 0xB10C** [comment]
fwiw: I'm also interested in running cyperpunkpay on my nixbitcoin instance as alternative to btcpayserver. btcpayserver has been a pain point for me and is way to big and resource hungry for my use-cases of receiving an occasional tip/donation.

Might build an out-of-tree module at some point. @prusnak thanks for https://github.com/NixOS/nixpkgs/pull/159879

**Comment by prusnak** [comment]
@0xB10C feel free to contribute the module to nixpkgs. also you can add yourself as a co-maintainer.
