### ISSUE TITLE
Feedback and minor improvements to the install.md

### ISSUE THREAD

**Issue by 0xB10C** [fort-nix/nix-bitcoin#49]
I've recently deployed a nix-bitcoin node to a VirtualBox following the instructions provided in `docs/install.md`. I detail some feedback and minor improvements below.
 
#### 1) to '1.4. Create Host Adapter in VirtualBox':
Add `vboxmanage hostonlyif create` to the manual. Has the same effect as
`Open VirtualBox -> File -> Host Network Manager -> Create` but doesn't use the GUI which might not be available on headless setups. 

#### 2) to '2.2. Install latest Nix in "multi-user mode" with GPG Verification'
Using `curl -o install-nix-2.2.1 https://nixos.org/nix/install` saves the install script with version 2.2.1 in the filename. This could be confusing in the future when `curl https://nixos.org/nix/install` gets you a newer version. I'd just write `curl -o install-nix https://nixos.org/nix/install` in the manual (of course change the filename in the following lines too). 

#### 3) to '3.1. Clone this project'
While `git clone https://github.com/jonasnick/nix-bitcoin` still works, it would be cleaner clone from `https://github.com/fort-nix/nix-bitcoin`. This seems like a relikt from the recent repository transfer to the fort-nix Organisation. For the unknowing user cloning from `jonasnick/nix-bitcoin` seems like cloning from a fork.

#### 4) to '3.1 Setup environment'
On low-end machines `nix-shell` takes quite some time and comes with a high CPU load, while not giving any output (at first). Usually making users skeptical whats being done in the background. Adding a simple "The nix-bitcoin environment is being setup. This might take a while." would be an improvement here I guess. If that's not possible a note in the `install.md` might be helpful.

**Comment by jonasnick** [comment]
Thanks for the feedback. Sounds all very reasonable.

**Comment by nixbitcoin** [comment]
Thanks for the great feedback! Looking forward to your feedback when you decide to install nix-bitcoin on standalone hardware.
