### ISSUE TITLE
deploy fails after updating to v0.0.74

### ISSUE THREAD

**Issue by alumbigi** [fort-nix/nix-bitcoin#514]
within nix-shell:

- `update-nix-bitcoin` runs as expected
- `deploy` throws an error and fails:

```
+ /nix/store/8lr32ri9vc07iqkari730cqzpgr6qlyh-populate.nixos.nixpkgs
sending incremental file list
rsync: [generator] failed to set permissions on "/var/src/nixpkgs/pkgs/development/libraries/readline/update-patch-set.sh": Operation not supported (95)
```

Deploying from Intel Mac running Nix 2.9.1 onto node running Nixos 21.11

**Comment by erikarvstedt** [comment]
This is fixed by the instructions in `Note for krops users on macOS` (https://github.com/fort-nix/nix-bitcoin/releases/tag/v0.0.74).

**Comment by alumbigi** [comment]
Thank you, I had missed those instructions. After following deploy works.
