### ISSUE TITLE
Restrict directory access for services

### ISSUE THREAD

**Issue by jonasnick** [fort-nix/nix-bitcoin#53]
We're already restricting access relatively okay by giving every service its own user. However there's at least one problem: the classic way to gain persistence as an unprivileged user is to add something similar to a `.bashrc` file into the users home which is then executed every time the user logs in. We should make that impossible by not giving access to the users home directory. This would in principle work right now already through systemd's `ProtectHomes`, except that the users home directories are often set to the services data directory, instead of `/home`.

**Comment by nixbitcoin** [comment]
I'll take care of this
