### ISSUE TITLE
Add developer docs

### ISSUE THREAD

**Issue by erikarvstedt** [fort-nix/nix-bitcoin#557]
Document dev tooling and best practices for developing and debugging nix-bitcoin.

**Comment by jonasnick** [comment]
Good idea. This could take the form of a `CONTRIBUTING.md`, `ARCHITECTURE.md`, `example-module.nix` and/or [`developer-notes.md`](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md).
