### ISSUE TITLE
mempool.nixbitcoin.org address lookup error

### ISSUE THREAD

**Issue by DanConwayDev** [fort-nix/nix-bitcoin#558]
Thanks for working on such a great project!

Address lookups on nixbitcoin.org are producing the error ""Error loading address data. (Connection to server lost, please retry)".

Compare:
https://mempool.nixbitcoin.org/address/bc1qn9cfjzpldsvqty2ff57gmyd2mlltnpr6g64cge
https://mempool.space/address/bc1qn9cfjzpldsvqty2ff57gmyd2mlltnpr6g64cge

#505

**Comment by erikarvstedt** [comment]
This is probably an upstream bug: https://github.com/mempool/mempool/issues/2246

I've now restarted the mempool instance on nixbitcoin.org.

**Comment by DanConwayDev** [comment]
I can confirm that the restart fixed the error.
