### ISSUE TITLE
lnd daemon requires the getpeerinfo bitcoind rpc method

### ISSUE THREAD

**Issue by ekimber** [fort-nix/nix-bitcoin#562]
I don't know why `getpeerinfo` is required by lnd, but it is. Also it is not obvious how to override this. My solution was to create my own whitelist:
```
            services.bitcoind = {
              enable = true;
              rpc.users.public.rpcwhitelist = import ./rpc-whitelist.nix;
            };
```

**Comment by erikarvstedt** [comment]
How can I reproduce this?
Searching the lnd repo (rev `d9e32f39c2687c23cc122901ee2d5de5d35879f0`), string `getpeerinfo` only shows up in files `lnwallet/test/test_interface.go`, `routing/chainview/interface_test.go`.
These seem to be irrelevant for runtime behavior.

**Comment by erikarvstedt** [comment]
You can simplify the workaround by just setting `rpc.users.public.rpcwhitelist = [ "getpeerinfo" ]` (the list elements of all definitions are merged).

**Comment by ekimber** [comment]
The `getpeerinfo` request is made by the LNWL module but the actual calling code is in the btcsuite/btcwallet repo
I've realised this issue will only appear with bitcoind pruning, perhaps that is why you have not seen it before. In the case that pruning is active, Lnd will fetch missing blocks from peers. Therefore it needs the peer info RPC call. Possibly others as well, I've not tested it extensively but after adding to the whitelist the node stood up without further errors.
