### ISSUE TITLE
Add torq: a capital management tool for LN routing nodes

### ISSUE THREAD

**Issue by mmilata** [fort-nix/nix-bitcoin#581]
https://github.com/lncapital/torq

**Comment by ekimber** [comment]
There is no torq nixos package and rather than try to package it, I have created a module for torq using podman oci containers. I am happy to share that, though I'm not sure it is suitable for inclusion into nix-bitcoin as it is rather a different way of doing things compared to the other modules.

**Comment by prusnak** [comment]
Since Torq is written in Go and requires only PostgreSQL it should be trivial to get it working in Nixpkgs / Nix-Bitcoin.

**Comment by mmilata** [comment]
Tried [packaging it](https://github.com/mmilata/nixpkgs/blob/torq/pkgs/applications/blockchains/torq/default.nix) but running into an error when building the go module dependencies:
```
go: downloading go.opentelemetry.io/otel/internal/metric v0.27.0
github.com/lncapital/torq/pkg/lnd_connect imports
        github.com/lightningnetwork/lnd/macaroons imports
        github.com/lightningnetwork/lnd/kvdb imports
        github.com/lightningnetwork/lnd/kvdb/etcd imports
        go.etcd.io/etcd/server/v3/embed imports
        go.opentelemetry.io/otel/semconv: no required module provides package go.opentelemetry.io/otel/semconv; to add it:
        go get go.opentelemetry.io/otel/semconv
github.com/lncapital/torq/pkg/lnd_connect imports
        github.com/lightningnetwork/lnd/macaroons imports
        github.com/lightningnetwork/lnd/kvdb imports
        github.com/lightningnetwork/lnd/kvdb/etcd imports
        go.etcd.io/etcd/server/v3/embed imports
        go.opentelemetry.io/otel/exporters/otlp imports
        go.opentelemetry.io/otel/sdk/metric/controller/basic imports
        go.opentelemetry.io/otel/metric/registry: no required module provides package go.opentelemetry.io/otel/metric/registry; to add it:
        go get go.opentelemetry.io/otel/metric/registry
```
https://gist.github.com/mmilata/f24e471e6903c9469d0264c7dc14dec0

Running `go build` on torq repo works fine, running `go mod vendor` produces the same error.

**Comment by prusnak** [comment]
> Tried [packaging it](https://github.com/mmilata/nixpkgs/blob/torq/pkgs/applications/blockchains/torq/default.nix) but ran into an error when building the go module dependencies:

Opened an upstream issue here: https://github.com/lncapital/torq/issues/320

**Comment by ohenrik** [comment]
I have applied a fix on main, let me know if it works or not.

But be aware that we are currently working on main so this cannot be relied on to work. To make sure you have a working version I suggest using a tagged version. I can create a new version number for you if main is working now.

**Comment by mmilata** [comment]
The package builds fine against current main, thanks @ohenrik! Can you please create tagged version? I'll open nixpkgs PR afterwards - who wants to be a co`maintainer`?

**Comment by prusnak** [comment]
@mmilata feel free to add me as co-maintainer

**Comment by ohenrik** [comment]
Great! I'll create a new tag tomorrow, we discovered a bug that we would like to include first. Hope that is ok :)

**Comment by mmilata** [comment]
a package https://github.com/NixOS/nixpkgs/pull/211293

**Comment by prusnak** [comment]
> a package [NixOS/nixpkgs#211293](https://github.com/NixOS/nixpkgs/pull/211293)

Merged into Nixpkgs 👍

**Comment by prusnak** [comment]
@mmilata lndhub.go has similar architecture - binary in go which requires postgresql - feel free to peek at https://github.com/fort-nix/nix-bitcoin/pull/519 to see how torq module could look like: https://github.com/fort-nix/nix-bitcoin/blob/7b508603830337d4b90b75339517ab265056f310/modules/lndhub-go.nix

**Comment by ohenrik** [comment]
@mmilata You can use the tag v0.16.13 and onwards. We will soon make a new official release (latest).

**Comment by mmilata** [comment]
Module #592 should be in a reasonably working state, feel free to test it.

**Comment by mmilata** [comment]
torq went closed source so this is probably not interesting anymore
