### ISSUE TITLE
LNBits will never work on nix-bitcoin?

### ISSUE THREAD

**Issue by we-do-it-lu** [fort-nix/nix-bitcoin#585]
Migrating from Raspiblitz to  nix-bitcoin. Really new on nixOS so still figuring out how this all works.
I met and discussed with a few nix-bitcoin fans and the impression I have is it would be impossible the have LNBits "nixified".
I love and use LNBits, not having it on nix is a shame, is the juice worth the squeeze? 

Could you give me a short statement or hashtag about what you think of LNBits and why you think it's "un-nixified"?

**Comment by prusnak** [comment]
LNbits already use Nix flakes in their upstream repo (although this is currently broken in master) and there is also this effort to package LNbits into Nix without flakes: https://github.com/fort-nix/nix-bitcoin/pull/496

So I don't really think that LNbits cannot be nixified. Frankly, there is a lot more complex software packaged in the Nixpkgs.

**Comment by dpc** [comment]
Everything can (and eventually will) be nixified.

**Comment by jonasnick** [comment]
@we-do-it-lu As the other's have said, it's not impossible. But there needs to be someone who is willing to maintain packages and/or modules in the long run. For some projects this is easier and for others it's harder. LNBits appears to be on the latter side of the spectrum which is presumably why you got the impression that this would be impossible.

**Comment by we-do-it-lu** [comment]
Thank you it helped me understand what it means and what the challenges are when it comes to maintaining packages etc.
