### ISSUE TITLE
LND needs an update

### ISSUE THREAD

**Issue by mariaa144** [fort-nix/nix-bitcoin#605]
I think I'm up-to-date on nix-bitcoin and my LND is `version 0.15.5-beta`. I have heard there are important patches in the most recent releases of LND.

https://github.com/lightningnetwork/lnd/releases/tag/v0.16.2-beta

**Comment by prusnak** [comment]
lnd 0.16.2 is ready in nixpkgs-unstable

all that needs to be done is bump nixpkgs-unstable in this reo

**Comment by jonasnick** [comment]
@mariaa144 The new release (0.0.91) contains lnd 0.16.2.
