### ISSUE TITLE
Update to bitcoind 25.0

### ISSUE THREAD

**Issue by erikarvstedt** [fort-nix/nix-bitcoin#611]
Blocked by https://github.com/bitcoin/bitcoin/issues/27722.
Due to this bug, bitcoind hangs indefinitely during shutdown when a RPC request was aborted previously.
In nix-bitcoin, bitcoind is eventually killed by systemd (default: after 30 min).

If you want to run v25.0 anyway, add the following to your config:
```nix
services.bitcoind.package = pkgs.bitcoind;
```

**Comment by fanquake** [comment]
25.1 is now available, and should contain the fix neccesary to unblock this.

**Comment by jonasnick** [comment]
Merged and released. Thanks @fanquake @prusnak!
