### ISSUE TITLE
Fix spark-wallet price lookup

### ISSUE THREAD

**Issue by nixbitcoin** [fort-nix/nix-bitcoin#62]
Spark-wallet with `nix-bitcoin-services.allowTor` doesn't allow looking up price. Using torsocks to wrap the price request gives an error. Should be fixed ASAP if we merge #52 before. 

Upstream issue: https://github.com/shesek/spark-wallet/issues/78

**Comment by 0xB10C** [comment]
Fixed in Upstream.
