### ISSUE TITLE
Stop using OpenSSL 1.1

### ISSUE THREAD

**Issue by jonasnick** [fort-nix/nix-bitcoin#632]
We will be able to remove openssl 1.1, since the master branch of [joinmarket](https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1517) and [python-bitcointx](https://github.com/Simplexum/python-bitcointx/issues/76) do not require openssl 1.1 anymore.

**Comment by jonasnick** [comment]
The recent [joinmarket release](https://github.com/JoinMarket-Org/joinmarket-clientserver/releases/tag/v0.9.10) updated the pyopenssl dependency and should therefore not require openssl 1.1 anymore.

**Comment by erikarvstedt** [comment]
Joinmarket still requires openssl 1.1: https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1613

**Comment by kristapsk** [comment]
JoinMarket master has been updated to python-bitcointx 1.1.4 and should not require OpenSSL 1.1 anymore.

**Comment by erikarvstedt** [comment]
@kristapsk, thanks! Fixed in #662.

**Comment by jonasnick** [comment]
#662 has been merged
