### ISSUE TITLE
BTCPayserver on Postgres 15: Permission denied for schema public

### ISSUE THREAD

**Issue by irusensei** [fort-nix/nix-bitcoin#657]
Hi. Setting PostgreSQL to 15 causes BTCPayserver and NBXplorer to throw the following error:

```
Exception data:
    Severity: ERROR
    SqlState: 42501
    MessageText: permission denied for schema public.
    Position: 14
    File: aclchk.c
    Line: 3650
    Routine: aclcheck_error    
```

Version 15 revoked permissions for all users https://www.postgresql.org/about/news/postgresql-15-released-2526. It seems version 14 allows any user to create a table.

If I'm not mistaken setting system.stateVersion to some recent will default to version 15.

I've tried `grant all on schema public` to the nbxplorer and BTCPayServer users but the error persists. A bit confused about this since the module specifically states that tables and users are to be created.

**Comment by erikarvstedt** [comment]
This issue only appears on nixos-unstable which isn't supported by nix-bitcoin.
We'll tackle the upgrade to postgresql 15 in the upcoming 23.11 release.
See https://github.com/NixOS/nixpkgs/pull/254268#issuecomment-1742073204 and the following comment for more info.
