### ISSUE TITLE
check out crate2nix for electrs builds

### ISSUE THREAD

**Issue by jb55** [fort-nix/nix-bitcoin#66]
I'm slowly in the process of upstreaming some of this stuff to nixos/nixpkgs. I noticed electrs was crashing on some blocks for some reason so I updated to the latest version, only to find that the rust packages in whatever rust channel nixpkgs was using was out of date.

there's a handy tool called [crate2nix](https://github.com/kolloch/crate2nix) which does fully self contained packaging of cargo projects. I'm giving it a spin now, just thought I'd mention it incase we want to switch to it in here for more reliable builds.

**Comment by nixbitcoin** [comment]
This is definitely something we're interested in. Could you share the resulting crate2nix expression so we can start using fully self contained packaging for electrs?

**Comment by jb55** [comment]
here's the branch I've been working on:

https://github.com/jb55/electrs/commits/master

to install crate2nix I cloned it and ran this because I didn't want to use their pinned nixpkgs:

```bash
nix-build --cores 14 -E 'with import <nixpkgs> {}; callPackage ./default.nix { inherit pkgs; }'
nix-env -i ./result
```

then I just ran

```bash
$ crate2nix generate
```
in the electrs path. I had to fix up the generated rocksdb derivation since it seemed broken, I left that as a separate commit so you can check it out.
