### ISSUE TITLE
Increase mempool historicals window size

### ISSUE THREAD

**Issue by OliverOffing** [fort-nix/nix-bitcoin#663]
It looks like mempool is currently storing/caching 1 (one) week worth of mempool data. Which means it's deleting data older than 7 days. This prevents me from seeing the charts for what the mempool looked like a month ago.

Is there an option available / is it possible to add an option to `nix-bitcoin`  that would prevent the deletion of older mempool data?

**Comment by erikarvstedt** [comment]
I can't reproduce this.
The mempool instance on nixbitcoin.org runs with the default settings and shows [1 year of mempool history](https://mempool.nixbitcoin.org/graphs/mempool#4y) when clicking on the `4Y` timespan button.

**Comment by erikarvstedt** [comment]
Feel free to reopen if this issue persists.

**Comment by OliverOffing** [comment]
Confirming the data (from Nov 29 on) is still there. I guess the database must've been re-created when I switched from the old method of having mempool on nix-bitcoin [to the new method](https://github.com/fort-nix/nix-bitcoin/pull/505).

**Comment by erikarvstedt** [comment]
The mempool extension flake and the new core module are equivalent. 
nixbitcoin.org also switched to the new core module, and it still has the complete history since the mempool instance started in Dec. 2022.

**Comment by OliverOffing** [comment]
Yeah but I was using [the `fetchTarball` method](https://github.com/fort-nix/nix-bitcoin-mempool/blob/1bad7985bbbc98f4223410bc432c1f987654e6d4/README.md#install), not flakes.

**Comment by erikarvstedt** [comment]
This has no effect on the resulting mempool service.
