### ISSUE TITLE
Support Bitcoin Knots as alternative to Bitcoin Core?

### ISSUE THREAD

**Issue by kristapsk** [fort-nix/nix-bitcoin#664]
So that people have choice.

**Comment by erikarvstedt** [comment]
Here's how to use Knots instead of Core:
```nix
services.bitcoind.package = let
  pkgsUnstable = import (builtins.fetchTarball {
    # unstable (2023-12-12)
    url = "https://github.com/NixOS/nixpkgs/archive/666fc80e7b2afb570462423cb0e1cf1a3a34fedd.tar.gz";
    sha256 = "1j4ahdm49pbw5s1sw0vc0l12s1zxlnw0sjvnljxhdjbsvgbjsl7m";
  }) {};
in
  pkgsUnstable.bitcoind-knots;

```

When the latest Knots 25.1 release has arrived in the stable nixpkgs channel, you can simply do this instead:
```nix
services.bitcoind.package = pkgs.bitcoind-knots;
```

**Comment by plebhash** [comment]
> To use Knots instead of Core, add this to your config:
> 
> services.bitcoind.package = config.nix-bitcoin.pkgs.bitcoind-knots;

@erikarvstedt is there a way to run both?

**Comment by erikarvstedt** [comment]
Let's discuss this on Matrix and share back the results later. I've sent you a PM on Matrix.
