### ISSUE TITLE
bitcoind debug.log

### ISSUE THREAD

**Issue by OliverOffing** [fort-nix/nix-bitcoin#665]
I wanted to contribute to https://github.com/bitcoin-data/block-arrival-times but I just noticed I don't have old log data. What would be the best way to either increase journald's max log size for just the `bitcoind` service, or alternatively have `bitcoind` write to `debug.log`?

**Comment by 0xB10C** [comment]
nix-bitcoin sets `nodebuglog=1` by default 

https://github.com/fort-nix/nix-bitcoin/blob/1d73b21f108cfddc928395bedd1119fc83dff489/modules/bitcoind.nix#L286

You can overwrite this with, e.g., `debuglogfile=debug.log` in `extraConfig`:

```nix
services.bitcoind.extraConfig = ''
  debuglogfile=debug.log
'';
```

**Comment by jonasnick** [comment]
Hi @OliverOffing. You can increase the journal size to 8 GB, for example, by adding
```
services.journald.extraConfig = "SystemMaxUse=8G";
```
to your configuration. You can verify that this worked by checking the logs of the journal:
```
journalctl -b -u systemd-journald
```

**Comment by OliverOffing** [comment]
This is very useful. Thanks all!
