### ISSUE TITLE
LND v0.17.3-beta is released

### ISSUE THREAD

**Issue by mariaa144** [fort-nix/nix-bitcoin#672]
Maybe I'm not updating correctly but my LND is still on version `0.17.0-beta`. I believe I'm tracking the release changes. `inputs.nix-bitcoin.url = "github:fort-nix/nix-bitcoin/release";`

```
> lnd --version
lnd version 0.17.0-beta commit=
```

https://github.com/lightningnetwork/lnd/releases

**Comment by prusnak** [comment]
> It looks like nixpkgs is still on 0.17.0-beta.

Feel free to send a pull request with an update to latest.

**Comment by jpentland** [comment]
Looks like nixpkgs is now on v0.17.4-beta, on both master and unstable, so this can be closed.

**Comment by jonasnick** [comment]
thanks @jpentland for the reminder
