### ISSUE TITLE
Add ln-vortex

### ISSUE THREAD

**Issue by nerd2ninja** [fort-nix/nix-bitcoin#697]
"Vortex is a tool to allow users to open lightning channels in a collaborative transaction when using [lnd](https://github.com/lightningnetwork/lnd) and [Core Lightning](https://github.com/ElementsProject/lightning)"

https://github.com/ln-vortex/ln-vortex

Genuinely apologize about not spending enough time to learn how to write a flake myself so this could be a PR instead of an issue. One day, one day.

**Comment by seberm** [comment]
I doubt the support for ln-vortex will be added into nix-bitcoin. The project seems abandoned (This repository has been archived by the owner on Sep 25, 2023. It is now read-only.). I think this issue can be closed (@erikarvstedt ).

**Comment by nerd2ninja** [comment]
If ln-vortex is not desired, then surely at least something that enables about the same capability ought to be. How about "nolooking" which is payjoin for lightning channels. Makes opening lightning channels cheaper.

**Comment by seberm** [comment]
I can help you prepare PR which adds support for such functionality / plugin in nix-bitcoin. But still, I am not convinced that even [nolooking](https://github.com/payjoin/nolooking) project is in a good state :/ - no project activity, the latest commit almost one year ago and it's still **very** experimental.

**Comment by jonasnick** [comment]
I think we'd be happy to add more useful software to nix-bitcoin, but we don't add unmaintained or very experimental projects because the maintenance burden is generally not worth it. Both lnvortex and nolooking fall into that latter category.

**Comment by nerd2ninja** [comment]
Well, I guess I'm out of software for this purpose then. There's Peach Bitcoin's "Group Hug", but its really just a batch and not a payjoin. I'll open a new issue if I find something better maintained.
