### ISSUE TITLE
`useVersionLockedPkgs = true` causes build error

### ISSUE THREAD

**Issue by kmajs** [fort-nix/nix-bitcoin#709]
After upgrading to NixOS 24.05 and setting `useVersionLockedPkgs = true`, I get the following error:
```
$ nixos-rebuild switch --flake .#host1 --target-host "root@host1"
...
error: Neither nixpkgs.system nor any other option in nixpkgs.* is meant
 to be read by modules and configurations.
 Use pkgs.stdenv.hostPlatform instead.
```
My flake input is `nix-bitcoin.url = "github:fort-nix/nix-bitcoin/release"`.

(Prior to upgrading my system, NixOS 23.11 worked with the default `useVersionLockedPkgs = false`.)

**Comment by kmajs** [comment]
In case anyone else runs into this later, it looks like this is happening when the `system` argument is omitted in the call to `nixpkgs.lib.nixosSystem`:
```
...
nixosConfigurations.bitcoinNode = nixpkgs.lib.nixosSystem {
  system = "x86_64-linux";   #required if useVersionLockedPkgs = true
  modules = [
    nix-bitcoin.nixosModules.default
    ({ ... }: {
      ...
      nixpkgs.system = "x86_64-linux";  # alternatively, can be set modularly
    })
  ];
};
```

When `useVersionLockedPkgs = true`, `config.nixpkgs.system` is used to create `nix-bitcoin.pkgs`, so it needs to be defined.

**Comment by erikarvstedt** [comment]
Note that setting `system` is **always** required with `lib.nixosSystem`, regardless of whether `useVersionLockedPkgs` is enabled or not.

**Comment by kmajs** [comment]
Thanks, I've added the argument for the nix-bitcoin machine. I think I've been able to omit `system` for my other `nixosConfigurations` because I'm using `nixpkgs.hostPlatform` instead. Apparently, if using a recently generated `hardware-configuration.nix`, `system` [does not need to be specified](https://github.com/NixOS/nixpkgs/blob/a421a1af26aad6115b4fc6565a5b0c01144229e9/nixos/modules/misc/nixpkgs.nix#L309). I don't fully understand all the platform/system options in nixpkgs, but it's working now, so I'll keep it. :)

**Comment by martijnboers** [comment]
Couldn't escape this error, set the system in `nixosSystem` call, in `hardware-configuration.nix` and like @kmajs said. Using unstable. 

```
error:
       … while calling the 'head' builtin
         at /nix/store/hpimnbshj9a3j18ja8hmxfsh76khxc66-source/lib/attrsets.nix:1534:13:
         1533|           if length values == 1 || pred here (elemAt values 1) (head values) then
         1534|             head values
             |             ^
         1535|           else

       … while evaluating the attribute 'value'
         at /nix/store/hpimnbshj9a3j18ja8hmxfsh76khxc66-source/lib/modules.nix:1084:7:
         1083|     // {
         1084|       value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |       ^
         1085|       inherit (res.defsFinal') highestPrio;

       … while evaluating the option `system.build.toplevel':
       … while evaluating definitions from `/nix/store/hpimnbshj9a3j18ja8hmxfsh76khxc66-source/nixos/modules/system/activation/top-level.nix':
       … while evaluating the option `warnings':
       … while evaluating definitions from `/nix/store/hpimnbshj9a3j18ja8hmxfsh76khxc66-source/nixos/modules/system/boot/systemd.nix':
       … while evaluating the option `systemd.services.bitcoind.serviceConfig':
       … while evaluating definitions from `/nix/store/v847q35kdv8jdl1h1i25nrdbkayajvnd-source/modules/bitcoind.nix':
       … while evaluating the option `services.bitcoind.package':
       … while evaluating the option `nix-bitcoin.pkgs':
       … while evaluating definitions from `/nix/store/hpimnbshj9a3j18ja8hmxfsh76khxc66-source/flake.nix':
       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: The option `nix-bitcoin.useVersionLockedPkgs' in `<unknown-file>' is already declared in `/nix/store/hpimnbshj9a3j18ja8hmxfsh76khxc66-source/flake.nix'.
```

I've forked the project and removed the option for now, this works.
