### ISSUE TITLE
c-lightning plugins

### ISSUE THREAD

**Issue by jb55** [fort-nix/nix-bitcoin#71]
Would be nice to make it easy to load clightning plugins:

- [x] Package pylightning
- [ ] Package [lightningd/plugins](https://github.com/lightningd/plugins) plugins and all the python dependencies required by them
- [ ] Add plugins option to clightning module

**Comment by jonasnick** [comment]
Yup that's definitely something we wanted to do.

**Comment by jb55** [comment]
First thing to do here is get pylightning packaged, then this should be pretty straightforward.

https://github.com/NixOS/nixpkgs/pull/68311

**Comment by jonasnick** [comment]
Fwiw pylightning was already packaged in nix-bitcoin https://github.com/fort-nix/nix-bitcoin/blob/master/pkgs/pylightning/default.nix but having it upstream is better obviously.
