### ISSUE TITLE
lnd fails to start with v0.0.109 

### ISSUE THREAD

**Issue by suorcd** [fort-nix/nix-bitcoin#713]
After changing to tag v0.0.109, lnd no longer connects to bitcoind.
Looking further into the issue, it seems like the rpcpass is getting set incorrectly.

Switching back to v0.0.108 and the correct rpcpass is set/used.

**Comment by erikarvstedt** [comment]
I can't reproduce this. Please share some logs.

While investigating this I found an other minor bitcoind RPC related bug which is fixed in #714.

**Comment by suorcd** [comment]
I it looks like PR #714 would fix my issue

```
Jul 08 08:49:06 nb00 bitcoind[414]: RPC User public not allowed to call method getpeerinfo
Jul 08 08:49:06 nb00 lnd[496]: 2024-07-08 08:49:06.624 [INF] HLCK: Health check: chain backend, call: 1 failed with: status code: 403, response: "", backing off for: 2m0s

```

the rpcpass was change was a red herring; it was not actually changing.

**Comment by suorcd** [comment]
I have verified that PR #714 fixed my issue.
