### ISSUE TITLE
Add `getnodeaddresses` to public bitcoind RPC whitelist?

### ISSUE THREAD

**Issue by erikarvstedt** [fort-nix/nix-bitcoin#721]
We recently added `getpeerinfo` to the public whitelist.
If we also added `getnodeaddresses`, lnd could use the public whitelist instead of defining a custom whitelist ([src](https://github.com/fort-nix/nix-bitcoin/blob/7dad87527f7aa366c3ecb67073405f15aa61c7f8/modules/lnd.nix#L189)).

In my view, RPC calls **should not** be added to the public whitelist if they
- affect the behavior of the bitcoind instance
- allow reading private wallet data

`getnodeaddresses` (https://chainquery.com/bitcoin-cli/getnodeaddresses) doesn't match these criteria and thus can be added to the public whitelist.

Was there a reason for not adding these calls in the first place?

cc @jonasnick

**Comment by jonasnick** [comment]
The reason for not adding these calls may have been privacy. I don't see a way to get the node's address other than `getnodeaddress`. But I'm not sure if there's actually no other way and there's no guarantee that it will stay like this in the future. On the other hand, it's not very costly to keep the custom whitelist.

**Comment by erikarvstedt** [comment]
`getnodeaddresses` returns addresses of peers the bitcoind instance has seen over its lifetime.
```bash
bitcoin-cli getnodeaddresses 0 | jq length
#=> 58390
```
It doesn't contain the node's own address (which, btw, would be trivial to detect for any process with WAN access).

So I think we should either whitelist `getnodeaddresses` along with `getpeerinfo` or remove `getpeerinfo` from the whitelist.
@jonasnick, what do you think?

**Comment by jonasnick** [comment]
> getnodeaddresses returns addresses of peers the bitcoind instance has seen over its lifetime.

Oh, right! I'd be fine with whitelisting it then.
