### ISSUE TITLE
support CLNRest core-lightning plugin

### ISSUE THREAD

**Issue by tim-tx** [fort-nix/nix-bitcoin#739]
[CLNRest](https://docs.corelightning.org/docs/rest) is a built-in core-lightning plugin providing some REST endpoints. I know we have clightning-rest, but I saw that in the [Zeus wallet](https://github.com/ZeusLN/zeus), clightning-rest is now deprecated while CLNRest is supported. It might be a nice enhancement to nix-bitcoin to support a built-in plugin with this functionality. As far as I can tell, nix-bitcoin uses the nixpkgs build of core-lightning where [CLNRest is omitted](https://github.com/NixOS/nixpkgs/blob/b00dba3ac026c80a10041d6bdc07dd31fd27b36a/pkgs/applications/blockchains/clightning/default.nix#L69) because it requires some extra Python dependencies.

**Comment by plebhash** [comment]
> As far as I can tell, nix-bitcoin uses the nixpkgs build of core-lightning where [CLNRest is omitted](https://github.com/NixOS/nixpkgs/blob/b00dba3ac026c80a10041d6bdc07dd31fd27b36a/pkgs/applications/blockchains/clightning/default.nix#L69) because it requires some extra Python dependencies.

that means we should first report/fix this on `nixpkgs`, right?

tagging package maintainers for awareness @jb55 @prusnak

**Comment by prusnak** [comment]
> tagging `nixpkgs` maintainers of `clightning` for awareness @jb55 @prusnak

feel free to send a PR to nixpkgs and I will review it

**Comment by plebhash** [comment]
digging a bit deeper, found some extra insights:

`CLNRest` was disabled from `nixpkgs` via this PR https://github.com/NixOS/nixpkgs/pull/293334 which is correlated to this WIP here: https://github.com/fort-nix/nix-bitcoin/pull/688

**Comment by chrisguida** [comment]
Have a look at https://github.com/daywalker90/clnrest-rs for the Rust version of clnrest, which should integrate a lot more easily with nix-bitcoin than the python version :)

**Comment by kaloudis** [comment]
> I can confirm that in Zeus 0.9.0 QR Code scanning no longer works for `clightning-rest`. This is a bug in Zeus, because `clightning-rest` is still supported, but deprecated. We'll fix this in #688, which will be merged soon.

This shouldn't be the case. Could you please file an issue in the Zeus repo with steps on how to recreate?

**Comment by erikarvstedt** [comment]
@kaloudis, the bug seems to have been fixed in Zeus 0.9.1.

**Comment by plebhash** [comment]
> @kaloudis, the bug seems to have been fixed in Zeus 0.9.1.

I ran `lndconnect-clightning` and scanned the QR code with Zeus 0.9.1

Zeus automatically chooses the following Node interface: `[DEPRECATED] Core Lightning (c-lightning-REST)`

When I try to connect, I get `Error: SOCKS server general failure`

**Comment by erikarvstedt** [comment]
The error I got with 0.9.0 was that after scanning a QR code encoding a `c-lightning-rest://` URL, Zeus showed `lnd` as the node type and failed to add the node after manually switching the node type to `clightning-rest`.

**Comment by jonasnick** [comment]
clnrest has been merged in #688
