### ISSUE TITLE
electrs breaks when the datadir variable is set

### ISSUE THREAD

**Issue by stevenroose** [fort-nix/nix-bitcoin#86]
I set the `electrs.dataDir` variable to some other location and I'm getting these logs in electrs:
```
Jul 10 08:55:55 dasilva-nix s4j86k2qkxz8473v1gy7xh3q5jfxp743-unit-script-electrs-pre-start[1425]: chmod: cannot access '/media/bitcoin-extra/electrs/startscript.sh': No such file or directory
```

So I suppose this startscript.sh script is somehow hard-coded into a path, but then the datadir is used to invoke it. Why isn't that script really hardcoded and just put in some hardcoded location?

**Comment by stevenroose** [comment]
So I guess it would either need a change like this:
```diff
diff --git a/modules/electrs.nix b/modules/electrs.nix
index 524bbd1..657c4c9 100644
--- a/modules/electrs.nix
+++ b/modules/electrs.nix
@@ -66,7 +66,7 @@ in {
       preStart = ''
         mkdir -m 0770 -p ${cfg.dataDir}
         chown 'electrs:electrs' ${cfg.dataDir}
-        echo "${pkgs.electrs}/bin/electrs -vvv ${index-batch-size} ${jsonrpc-import} --timestamp --db-dir ${cfg.dataDir} --daemon-dir /var/lib/bitcoind --cookie=${config.services.bitcoind.rpcuser}:$(cat /secrets/bitcoin-rpcpassword) --electrum-rpc-addr=127.0.0.1:${toString cfg.port}" > /var/lib/electrs/startscript.sh
+        echo "${pkgs.electrs}/bin/electrs -vvv ${index-batch-size} ${jsonrpc-import} --timestamp --db-dir ${cfg.dataDir} --daemon-dir /var/lib/bitcoind --cookie=${config.services.bitcoind.rpcuser}:$(cat /secrets/bitcoin-rpcpassword) --electrum-rpc-addr=127.0.0.1:${toString cfg.port}" > ${cfg.dataDir}/startscript.sh
         chown -R 'electrs:electrs' ${cfg.dataDir}
         chmod u+x ${cfg.dataDir}/startscript.sh
         '';    
```

Or like this:
```diff
diff --git a/modules/electrs.nix b/modules/electrs.nix
index 524bbd1..04e3ade 100644
--- a/modules/electrs.nix
+++ b/modules/electrs.nix
@@ -68,11 +68,11 @@ in {
         chown 'electrs:electrs' ${cfg.dataDir}
         echo "${pkgs.electrs}/bin/electrs -vvv ${index-batch-size} ${jsonrpc-import} --timestamp --db-dir ${cfg.dataDir} --daemon-dir /var/lib/bitcoind --cookie=${config.services.bitcoind.rpcuser}:$(cat /secrets/bitcoin-rpcpassword) --electrum-rpc-addr=127.0.0.1:${toString cfg.port}" > /var/lib/electrs/startscript.sh
         chown -R 'electrs:electrs' ${cfg.dataDir}
-        chmod u+x ${cfg.dataDir}/startscript.sh
+        chmod u+x /var/lib/electrs/startscript.sh
         '';    
       serviceConfig = {
         PermissionsStartOnly = "true";
-        ExecStart = "${pkgs.bash}/bin/bash ${cfg.dataDir}/startscript.sh";
+        ExecStart = "${pkgs.bash}/bin/bash /var/lib/electrs/startscript.sh";
         User = "electrs";
         Restart = "on-failure";
         RestartSec = "10s";
```
I guess I like the second one better. There is no need for the script to be in the datadir.

**Comment by jonasnick** [comment]
Both versions are fine, although I'd have a preference for the first one as this would mean that the startscript is always in the datadir vs. it is only when you use the default datadir. I think the second one also needs to make sure that `/var/lib/electrs` exists.

**Comment by stevenroose** [comment]
I agree with the "only sometimes in the datadir" issue. In principle it shouldn't be in the datadir, right? So we should kinda write it somewhere hidden. Not sure what are nix-conventional paths that packages can use, probably `/var/lib/name` is the one? I won't propose changing the default datadir, though.

Opinion, @nixbitcoin? Otherwise I can just PR the first change.

**Comment by jonasnick** [comment]
> In principle it shouldn't be in the datadir, right?

Yes, I agree. Perhaps it would be best to write it to a temporary dir? It's not supposed to persist or be written to anyway.

**Comment by nixbitcoin** [comment]
Yes, `startscript.sh` should be written to a temporary dir that only the electrs user has access to. 

The original reason for creating the startscript and not just running `${pkgs.electrs}/bin/electrs -vvv ${index-batch-size} ${jsonrpc-import} --timestamp --db-dir ${cfg.dataDir} --daemon-dir /var/lib/bitcoind --cookie=${config.services.bitcoind.rpcuser}:$(cat /secrets/bitcoin-rpcpassword) --electrum-rpc-addr=127.0.0.1:${toString cfg.port}` was to avoid exposing the bitcoin rpc password to processes running under other users. I'm running `ps -aux` from different users and can't seem to see any electrs commands except by running `ps -aux` under root or electrs. Would it be better to just get rid of `startscript.sh` and put all this stuff in `ExecStart`?

**Comment by jonasnick** [comment]
Right, if `$(cat /secrets/bitcoin-rpcpassword)` works in ExecStart should be equivalent security wise but simpler code wise.

**Comment by nixbitcoin** [comment]
ACK. @stevenroose do you want to take this one?

**Comment by stevenroose** [comment]
https://github.com/fort-nix/nix-bitcoin/pull/93

Gave it a shot.
