### ISSUE TITLE
Improve iOS users' lives

### ISSUE THREAD

**Issue by stefan-mihaila** [fort-nix/nix-bitcoin#94]
Sadly, the experience on iOS is deplorable. I can run Spark Wallet with [Onion Browser](https://onionbrowser.com/), but even that is frustrating because WebRTC doesn't work. Even if Spark Wallet would work flawlessly, it seems to me that it doesn't actually allow users to transfer funds on-chain, only off-chain. In consequence, iOS users have no option to send funds on-chain from their phones using their nix-bitcoin node.

I think that this can be mitigated by adding support to run lnd on clearnet in nix-bitcoin, in parallel or as an alternative to clightning. Sadly, it must be in clearnet as there is not any alternative to Orbot on iOS and it might not ever be one because... Apple. iOS users would then be able to use [Zap](https://zap.jackmallers.com) for both on-chain and off-chain transfers with their nix-bitcoin node.

**Comment by jonasnick** [comment]
Hm, if it's as painful on iOS as you're saying then that should be fixed. Would be easier if there was an iOS app for/alternative to spark, but if someone is motivated to add lnd I'd support it.

**Comment by cypherpunk2140** [comment]
Just to be clear, Spark Wallet with Onion Browser is the PWA version of Spark Wallet. There is no native version of Spark Wallet for iOS atm, even though one is stated to come soon™. If there would be (or an alternative), leaving aside the little inconvenient that it can't be run over tor, I would be happy with that.

In the mean time, I looked a little into trying to integrate `lnd` into nix-bitcoin. [Building is trivial](https://github.com/NixOS/nixpkgs/pull/65263/files#diff-890b4fb9d231f348f899b142a4a56e23). I unfortunately got stuck on starting the service for now. I will take another look at it in a few days.

**Comment by nixbitcoin** [comment]
I don't think adding clearnet functionality aligns with the nix-bitcoin networking model. If we do add this it should be an opt-in feature in configuration.nix. The inbound Tor HS model is crucial to the privacy and security of nix-bitcoin users. 

Would there by any way to use iOS's VPN API with Wireguard in a limited fashion to only tunnel zap/spark-wallet (soon™) from iOS to nix-bitcoin nodes?

**Comment by cypherpunk2140** [comment]
In my view, that was the idea, to add an option to run (only) lnd on clearnet in configuration.nix.

> Would there by any way to use iOS's VPN API with Wireguard in a limited fashion to only tunnel zap/spark-wallet (soon™) from iOS to nix-bitcoin nodes?

I am not sure that I understand your suggestion. Are you suggesting adding a Wireguard VPN server to nix-bitcoin and using iOS's VPN API to connect to that server? I am definitely open to give it a try. I'll try making the lnd service work over Tor first, then we'll see about how we can connect from iOS apps to it...

**Comment by nixbitcoin** [comment]
> Are you suggesting adding a Wireguard VPN server to nix-bitcoin and using iOS's VPN API to connect to that server?

Yes, seems like the only way to connect to a nix-bitcoin node from iOS without exposing the nix-bitcoin node to the clearnet, with all the security and NAT problems that entails. Although you lose a considerable degree of privacy against network adversaries when using Wireguard instead of Tor. 

Could Zap bundle Tor in their iOS App?

**Comment by cypherpunk2140** [comment]
> Could Zap bundle Tor in their iOS App?

Looks like Zap's iOS main contributor gave it a try already, but didn't manage to get it working for the time being: https://github.com/LN-Zap/zap-iOS/issues/62

**Comment by cypherpunk2140** [comment]
> Could Zap bundle Tor in their iOS App?

I had a chat with @ottosuess recently. He said that Zap could connect to lnd over tor, if it used REST instead of gRPC. I'll try to give him a hand with implementing REST in Zap, after getting https://github.com/fort-nix/nix-bitcoin/pull/107 ready for merge.

**Comment by nixbitcoin** [comment]
As far as I can tell Zap supports connecting over Tor on iOS since https://github.com/LN-Zap/zap-iOS/pull/272

Guide is available here: https://github.com/openoms/bitcoin-tutorials/blob/master/Zap_to_RaspiBlitz_through_Tor.md

@stefan-mihaila maybe think about documenting this nix-bitcoin specific in `docs/usage.md`
